### ISSUE TITLE
Bump google-auth-library-java to 1.0.0 (GA)

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-auth-library-java#101]
- [ ] Mark anything `@BetaApi` or `@Internal` that we want the flexibility to change later (requires adding a dependency on api-common) - only things unused in google-cloud-java and grpc-auth can be marked this way
- [x] Remove Guava from the surface
- [ ] Add back any features removed since 0.4.0 (to maintain compatibility with grpc-auth)
- [ ] Any other GA cleanup
- [x] drop guava-jdk5 support
- [x] Full end-to-end testing (#293)

**Comment by elharo** [comment]
Upgrade deps:

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <java.version>1.6</java.version>
    <project.google.http.version>1.19.0</project.google.http.version>
    <project.junit.version>4.12</project.junit.version>
    <project.guava.version>19.0</project.guava.version>
    <project.appengine.version>1.9.34</project.appengine.version>
  </properties>

**Comment by elharo** [comment]
I don't see any current places where we expose Guava in the public API. Do you know of any?

Do we want to remove the assorted deprecated methods?

**Comment by elharo** [comment]
Looks like jdk5 is already gone.

**Comment by TimurSadykov** [comment]
GA release happened with https://github.com/googleapis/google-auth-library-java/pull/704

let me know if something is still relevant, but missing
