### ISSUE TITLE
Regression between 1.13.0 and 1.14.0 when sharing `GoogleCredentials` object between different APIs

### ISSUE THREAD

**Issue by marcust** [googleapis/google-auth-library-java#1142]
I have been chasing an issue I had that a library bom update caused a regression in the way that I got permission exceptions without actually having changed anything: https://github.com/firebase/firebase-admin-java/issues/763

I pinned it down to a "regression" between 1.13.0 and 1.14.0 and the way that I am sharing the same Credentials Object between Sheets and Firebase APIs. My best guess would be that 84afdb8f8d41e781dc93f04626411e10b35689de usually would cause the token that had been initialised for Sheets to refresh before calling Firebase, making the call have the correct scopes and thus go through. 

I guess I should stop sharing the same object, I guess I had the asumption that this is an immutable representation of the Service Account JSON on disk, but it is apparently not (edit: I realised I create them `scoped`, even handing in the Sheets Scope, but it worked before). I am leaving that here for documentation purposes in case someone else runs into the issue. Not sure if there is actually a "fix" to that.

**Comment by wangyutongg** [comment]
Hi @marcust, Have you considered using Application Default Credentials? https://github.com/googleapis/google-auth-library-java/blob/main/oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java#L100

It will search the available credentials based on specific order. It should work for both APIs. Here are some docs: https://cloud.google.com/docs/authentication/provide-credentials-adc

**Comment by marcust** [comment]
I uses `SheetsScopes.SPREADSHEETS` which is `https://www.googleapis.com/auth/spreadsheets`. 

I do not really understand the rest of the comment, so what I was doing was reusing basically 
```
        return ServiceAccountCredentials
                .fromStream(serviceAccountResource.getInputStream())
                .createScoped(List.of(SheetsScopes.SPREADSHEETS));
```
and also put that into a Firebase Config:
```
 final FirestoreOptions firestoreOptions = FirestoreOptions.newBuilder()
                .setCredentials(credentials)
                .build();
```

 `GoogleCredentials.getApplicationDefault()`  is just a different way of creating the `GoogleCredentials`. I think it would have the same problem, as my issue was reusing the object and not the way I created it, or am I reading that wrong.

**Comment by wangyutongg** [comment]
Thank you for the code samples. Agree reusing the object is the issue here. I was suggesting trying calling `getApplicationDefault()` without scopes. The library will add some default scopes, enough for authorizing to most cloud APIs. We can see if the default scopes give you enough permission to access Sheet and Firestore APIs.

**Comment by marcust** [comment]
I am putting this scopes now in the individual config objects I use:
```
private static final List<String> SHEET_SCOPES = List.of(SheetsScopes.SPREADSHEETS);
private static final List<String> FIREBASE_SCOPES = List.of(
            "https://www.googleapis.com/auth/datastore",
            "https://www.googleapis.com/auth/cloud-platform");
``` 

I will close this now as there is not really anything to be done. Thank you.
