### ISSUE TITLE
Support Workload Identity Federation when using Azure Kubernetes Service

### ISSUE THREAD

**Issue by linnea-s** [googleapis/google-auth-library-java#1198]
We have been using GCP Workload identity federation to access resources in GCP from applications running in Azure Kubernetes Service. This is configured as documented here: https://cloud.google.com/iam/docs/workload-identity-federation-with-other-clouds#azure

This has previously worked well with [pod-managed identities in AKS](https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity). However that feature is in preview and will be removed at some point as it's being replaced by [Azure AD workload identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview). These features are the equivalent of Workload Identity in GKE, allowing workloads to impersonate Azure Managed Identities.

As currently documented, GCP Workload Identity Federation does not work with Azure AD workload identity on AKS. The Google auth library receives a HTTP 404 error when trying to fetch a token from IMDS. This is because Azure AD workload identity on AKS does not include a sidecar container for compatibility with apps using IMDS (`http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=...`). While it is possible to configure a sidecar container, [the documentation](https://learn.microsoft.com/en-us/azure/aks/workload-identity-migrate-from-pod-identity) explicitly states:
> The migration sidecar is not supported for production use. This feature is meant to give you time to migrate your application SDK's to a supported version, and not meant or intended to be a long-term solution.

In summary, the currently documented steps to use GCP Workload Identity Federation on Azure only work in Azure Kubernetes Service when using a feature which is in preview (and is being replaced) or a sidecar container which is not supported for production use.

I have found that I can probably use executable-sourced credentials to work around this, using a small Go application which uses the Azure Identity library to provide a token: https://gist.github.com/linnea-s/7ad2e2087e9d424cd278e9714b3b4ab8

However I think that this is not an ideal solution:
* The executable must be included in all applicable Docker application containers
* The executable is another piece to maintain
* It requires more CPU and memory

I believe it would be a benefit to many Google Cloud customers if the Google auth library either:
1. Supported Azure AD workload identity on AKS
2. Provided an API which allows the application to pass the token through a callback function

As an example of 2, here is a sample showing the API for impersonating an Azure Managed Identity from GCP when using the Microsoft authentication library for java (msal4j): https://gist.github.com/linnea-s/11cfd2695c54e7d4cdfdfb3e8ca01e2d#file-azureauthtest-java-L21

While it does not have the zero-code convenience of the Google auth library when using a credentials configuration file, it is more flexible in that any API can be used to provide the token without requiring an external executable.

**Comment by lsirac** [comment]
Hi @linnea-s,

Both options you're looking for are supported:
1. Use file-sourced credentials to point to the KSA token directly. See https://cloud.google.com/iam/docs/workload-identity-federation-with-kubernetes#aks.
2. We recently launched [credential suppliers](https://cloud.google.com/iam/docs/workload-identity-federation-with-kubernetes#aks).  This basically lets you pass the token through a callback function to the library like you're looking for.
