### ISSUE TITLE
Allow AWS Credentials to be provided at runtime

### ISSUE THREAD

**Issue by Gianlo98** [googleapis/google-auth-library-java#1210]
**Is your feature request related to a problem? Please describe.**
Currently, we cannot create an instance of `AwsCredentials` that uses a source other than environment variables to gather AWS Credentials. Therefore, it's not possible to retrieve these credentials at runtime because they must be preset as environment variables.

**Describe the solution you'd like**
Expand the functionality of `ExternalAccountCredentials` to allow it to create an instance of `AwsCredentials` not only from a JSON file but, for example, from an instance of s`oftware.amazon.awssdk.auth.credentials.AwsSessionCredentials`, or any similar entity that can be instantiated at runtime.

**Describe alternatives you've considered**
I had to create a custom class extending `GoogleCredentials` because extending `ExternalAccountCredentials` wasn't possible due to certain constructor arguments that are inaccessible.

**Comment by Gianlo98** [comment]
The proposed solution would also solve #1032

**Comment by lsirac** [comment]
Setting AWS creds at runtime would make the creds one time use. We are working on a feature that will enable this + refresh.

**Comment by lsirac** [comment]
Should be ready early Q4.

**Comment by abrown201193** [comment]
Hi @lsirac,
When you say early Q4 do you mean October/November of 2024 if so what is the status of this feature?
Thanks

**Comment by lsirac** [comment]
Hi @abrown201193, we'll have this implemented and released by the end of year. Apologies for the delay.

**Comment by abrown201193** [comment]
Hey @lsirac is this still on track for end of December? thanks!

**Comment by lsirac** [comment]
> Hey @lsirac is this still on track for end of December? thanks!

PR is up: https://github.com/googleapis/google-auth-library-java/pull/1336

**Comment by aeitzman** [comment]
Added support for using a custom implementation to supply AWS security credentials in https://github.com/googleapis/google-auth-library-java/pull/1336, released in v1.23.0.
