### ISSUE TITLE
Missing scopes using WIF when upgrading google-auth-library-java-oauth2-http from 1.13.0 to 1.14.0

### ISSUE THREAD

**Issue by torgeir** [googleapis/google-auth-library-java#1274]
Environment details:
1. Google Auth Library, Core
2. Github Actions, Workload Identity Federation
3. Java Version: 17
4. Upgrading google-auth-library-java-oauth2-http from 1.13.0 to 1.14.0

The code shown below

- works with GCP libraries bom v26.3.0, google-auth-library-credentials:1.14.0, google-auth-library-oauth2-http:1.13.0
- does not work with GCP libraries bom v26.3.0, google-auth-library-credentials:1.14.0, google-auth-library-oauth2-http:1.14.0
- does not work with GCP libraries bom v26.4.0 (which also has google-auth-library-credentials:1.14.0, google-auth-library-oauth2-http:1.14.0)

We are seing an error transitioning from 1.13.0 to 1.14.0, by moving from gcp libraries-bom v26.3.0 to v26.4.0 (also present for the new versions, like v26.22), on Github Actions using Workload Identity Federation to impersonate a service account that runs a kotlin integration test, that attempts to use the Admin Api like this:

```kotlin
val credentials =
  GoogleCredentials
    .getApplicationDefault()
    .createScoped(
      DirectoryScopes.ADMIN_DIRECTORY_GROUP_READONLY,
      DirectoryScopes.ADMIN_DIRECTORY_USER_READONLY)

val directory =
  Directory
    .Builder(
      GoogleNetHttpTransport.newTrustedTransport(),
      GsonFactory(),
      HttpCredentialsAdapter(credentials))
    .setApplicationName("<name>")
    .build()

val user = directory.users().get("<email>").execute()
```

The code runs fine locally, when run with credentials obtained like this

```
gcloud auth application-default login \
  --impersonate-service-account <sa>@<project_id>.iam.gserviceaccount.com \
  --scopes \
https://www.googleapis.com/auth/admin.directory.group.readonly,https://www.googleapis.com/auth/admin.directory.user.readonly,https://www.googleapis.com/auth/cloud-platform
```

After moving to google-auth-library-oauth2-http:1.14 the code fails on Github Actions using Workload Identity Federation.

Workload identity federation is set up like this:

```yaml
  <...>

  - name: WIF
    id: auth
    uses: google-github-actions/auth@v1
    with:
      workload_identity_provider: projects/<project_number>/locations/global/workloadIdentityPools/<pool-id>/providers/<provider_id>
      service_account: <sa>@<project_id>.iam.gserviceaccount.com
      token_format: access_token

  - name: Setup Google Cloud SDK
    uses: google-github-actions/setup-gcloud@v1

  <...>
```

The error we get is this

```
    GET https://admin.googleapis.com/admin/directory/v1/users/<some-user-in-the-org@org.tld>
    {
      "code": 403,
      "details": [
        {
          "@type": "type.googleapis.com/google.rpc.ErrorInfo",
          "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
          "domain": "googleapis.com",
          "metadata": {
            "method": "ccc.hosted.frontend.directory.v1.DirectoryUsers.Get",
            "service": "admin.googleapis.com"
          }
        }
      ],
      "errors": [
        {
          "domain": "global",
          "message": "Insufficient Permission",
          "reason": "insufficientPermissions"
        }
      ],
      "message": "Request had insufficient authentication scopes.",
      "status": "PERMISSION_DENIED"
    }
```

The wif setup results in a json token file of type "external_account" (with the fields "audience", "credential_source", "service_account_impersonation_url", "subject_token_type", "token_url", "type": "external_account") in the Github Actions run, which ends up using the classes `IdentityPoolCredentials` that inherits `ExternalAccountCredentials` in this repo when the `GoogleCredentials.getApplicationDefault()` is called.
It is initiated from `ExternalAccountCredentials.fromJson`.

The workaround we have found for this issue is introducing a call to .refresh() the access token

```kotlin
val credentials =
  GoogleCredentials
    .getApplicationDefault()
    .createScoped(
      DirectoryScopes.ADMIN_DIRECTORY_GROUP_READONLY,
      DirectoryScopes.ADMIN_DIRECTORY_USER_READONLY)

// workaround
credentials.refresh()

val directory =
  Directory
    .Builder(
      GoogleNetHttpTransport.newTrustedTransport(),
      GsonFactory(),
      HttpCredentialsAdapter(credentials))
    .setApplicationName("<name>")
    .build()

val user = directory.users().get("<email>").execute()
```

This workaround probably works as the following adds the scopes to the requested token request.

https://github.com/googleapis/google-auth-library-java/blob/v1.14.0/oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java#L174-L177

This issue is similar to #1186, and what was worked around in #1142, which leads me to believe that this is in fact a regression in the way scopes are handled when they are added with .createScoped() / used from workload identity federation.

Speculation:

Is it possible that the access token somehow previously would refresh before use, after we requested our wanted scopes?

No scopes are added here when the .json keyfile is read

https://github.com/googleapis/google-auth-library-java/blob/v1.14.0/oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java#L440

Best regards,
Torgeir

**Comment by TimurSadykov** [comment]
@lsirac can you please take a look? This does not seem to be the case for regular SA creds.

**Comment by torgeir** [comment]
For the record I have also forwarded this issue to GCP support, as suggested in the repo's Bug Report template.

> This does not seem to be the case for regular SA creds.

This also reflects our experience.

**Comment by lsirac** [comment]
Unfortunately I can't replicate this. I also don't see any changes between 1.13 -> 1.14 in this lib that would cause this.

Regarding your comments:
```
This workaround probably works as the following adds the scopes to the requested token request.

https://github.com/googleapis/google-auth-library-java/blob/v1.14.0/oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java#L174-L177
```
This code path is invoked regardless of the added refresh call. I'm not sure why adding this fixes the issue for you.. 

```
Is it possible that the access token somehow previously would refresh before use, after we requested our wanted scopes?
```
The library doesn't do this at least - the creds don't refresh before they are used. 

```
No scopes are added here when the .json keyfile is read

https://github.com/googleapis/google-auth-library-java/blob/v1.14.0/oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java#L440
```
This is WAI. It defaults to using the cloud platform scope (which some of the other auth libraries don't do). Then you are calling createScoped() [which creates a new IdentityPoolCredentials object with the scopes you specified](https://github.com/googleapis/google-auth-library-java/blob/v1.14.0/oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java#L248).

Also note that you are including the cloud platform scope with gcloud application-default login but not when using the lib. The library will default to use the GCP scope but not include it if you provide your own. 

Can you check which scopes are being passed [here](https://github.com/googleapis/google-auth-library-java/blob/v1.14.0/oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java#L174) when you don't call refresh() before hand?

**Comment by torgeir** [comment]
Too bad, cause we see this when bumping from 1.13 -> 1.14 is the only change we make. 

I don't have an easy way of testing your suggestion without building my own version of this lib to add logging, as this is run on github actions, which is more time than I can spare on this issue in the coming weeks.

Is there some kind og logging you could suggest that I could turn on to maybe provide more insights rather than having to change the code?

**Comment by lsirac** [comment]
Hey @torgeir, can you try updating to the latest version (v1.22.0)? Let us know if this is still an issue.

**Comment by TimurSadykov** [comment]
@torgeir please see explanation for the similar issue and fix for some other project: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/1329

**Comment by TimurSadykov** [comment]
Please reopen if neither of suggestions help
