### ISSUE TITLE
google-auth-library-java-oauth2-http: refresh() doesn't generate new token on each call in GKE

### ISSUE THREAD

**Issue by gaurav517** [googleapis/google-auth-library-java#1280]
OS type and version: Linux/Mac 
Java version: 11
version(s): `google-auth-library-java-oauth2-http:1.13.0`

#### Steps to reproduce

  1. Use [`OAuth2Credentials.refresh()` ](https://github.com/googleapis/google-auth-library-java/blob/aa047396112cbc0dd64f3fc147ed15f976c96bf0/oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java#L190C1-L190C1) method to generate access token and use[ OAuth2Credentials.getAccessToken()](https://github.com/googleapis/google-auth-library-java/blob/aa047396112cbc0dd64f3fc147ed15f976c96bf0/oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java#L146) to get the token in a loop.
  2. In local environment, a new access token is generated every time.
  3. In GKE environment, a new access token is generated initially and then only once in an hour (about 5 mins away from expiry), using same service account and same code.

#### Code example

I used following code to test the finding.

```java
package com.test;

import com.google.auth.oauth2.AccessToken;
import com.google.auth.oauth2.GoogleCredentials;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;

@RestController
@Slf4j
public class GcpController {
    String prevToken = "init";
    String prevExpiry = "init";
    @GetMapping(value = "/gcp/token")
    public ResponseEntity<String> getToken() {
        GoogleCredentials credentials;
        String hostName = System.getenv("HOSTNAME");
        log.info(hostName + ": gcp/token was called.");
        try {
            credentials = GoogleCredentials.getApplicationDefault();
        } catch (IOException err) {
            throw new RuntimeException(
                    "Unable to obtain credentials to communicate with the Cloud SQL API", err);
        }

        // Scope the token to ensure it's scoped to logins only.
        GoogleCredentials scoped = credentials.createScoped(
                "https://www.googleapis.com/auth/sqlservice.login");

        try {
            scoped.refresh();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        AccessToken accessToken = scoped.getAccessToken();
        if (!StringUtils.equals(prevToken, accessToken.getTokenValue())) {
            log.info(hostName + ": Token was refreshed. Previous expiry was: " + prevExpiry + ", new expiry is: " + accessToken.getExpirationTime());
            log.info(hostName + ": Old token: " + prevToken);
            log.info(hostName + ": New token: " + accessToken.getTokenValue());
            prevToken = accessToken.getTokenValue();
            prevExpiry = accessToken.getExpirationTime().toString();
        }
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.TEXT_PLAIN);
        return new ResponseEntity<>(hostName + "->" + accessToken.getTokenValue() + "\nexpiry->" + accessToken.getExpirationTime(), headers, HttpStatus.OK);
    }
}
```

#### External references such as API reference guides

In the [method documentation](https://github.com/googleapis/google-auth-library-java/blob/aa047396112cbc0dd64f3fc147ed15f976c96bf0/oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java#L185-L188), it says `Request a new token regardless of the current token state.`

So my expectation is that behaviour in local environment is right.. and it doesn't seem right in GKE environment.

**Comment by TimurSadykov** [comment]
Hi, thanks for the question!

The behavior of GKE is expected if you rely on a VM-provided credential. Access token is indeed cashed on environment level for approx. 55 min, just like you have discovered. 

The documentation you referring to is for the very base class, not a specific credential you eventually use. Most likely the actual type of credential in your case in ComputeEngineCredentials. Although I agree, base class documentation is misleading in this case, we will update that refresh behavior depends on actual credential type. 

Locally you are outside of GCE/GKE environment and you probably rely on some serviceaccount or usercredentials from gcloud. They don't cache. 

If you want local and GKE behaviors to match you need to set up prod environment with a ServiceAccount. One way to do that, that does no require any code change in your case: set the environment variable GOOGLE_APPLICATION_CREDENTIALS to the path of the JSON file that contains your service account key.

**Comment by gaurav517** [comment]
Thanks. It makes sense.

`If you want local and GKE behaviors to match you need to set up prod environment with a ServiceAccount.`: In my case I was using a Service Account both in GKE (using WLI) and local environment (using json key). I am assuming caching in some layer in GKE environment when using WLI (pod/node/metadata-server etc.) Unfortunately I couldn't find a good documentation for this yet.

**Comment by TimurSadykov** [comment]
Oh actually, even separate service account could be cached in some environments. Apparently it is true for GKE. So for the confusion. 

BTW, do you really need the token flow? For most services token flow is not used and SelfSignedJWT flow is used instead. In this no access token and no refresh required. 

This flow should be enabled by default when used with scopes. You can check having a breakpoint here, [here](https://github.com/googleapis/google-auth-library-java/blob/aa047396112cbc0dd64f3fc147ed15f976c96bf0/oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java#L914).

**Comment by TimurSadykov** [comment]
@gaurav517  In general, there is no practical difference. Either way, library makes sure the token is fresh on each request. Let us know if there is any scenario that is affected by differences in behavior.

**Comment by TimurSadykov** [comment]
please reopen if any more questions
