### ISSUE TITLE
Allow usage of ExternalAccountCredentials custom implementation

### ISSUE THREAD

**Issue by hynek5** [googleapis/google-auth-library-java#1321]
I'm trying to authenticate to GCP via Workload Identity Federation using Keycloak as OIDC provider. I created my own implementation extending from `ExternalAccountCredentials` in simillar fashion as `IdentityPoolCredentials` to meet my needs.
In case of Keycloak I need to override `com.google.auth.oauth2.ExternalAccountCredentials#retrieveSubjectToken`, but I'm getting ClassCastException  as method
`com.google.auth.oauth2.ExternalAccountCredentials#buildImpersonatedCredentials` is trying to cast sourceCredentials to `IdentityPoolCredentials`

It would be nice if there was a way to work around this and have posibility to use your own implementation.

I have considered doing some customization on Keycloack side, but this could be a potential security risk. The other alternative would be to create some temporary file with an access token, but this is another security risk

Attaching  `IdentityPoolKeycloakCredentials` for clarity.
[IdentityPoolKeycloakCredentials.zip](https://github.com/googleapis/google-auth-library-java/files/13193741/IdentityPoolKeycloakCredentials.zip)

**Comment by lsirac** [comment]
Hi hynek5, #1336 provides a way to provide your own retrieveSubjectToken() implementation.

**Comment by aeitzman** [comment]
Added support for using a custom implementation to supply a subject token in https://github.com/googleapis/google-auth-library-java/pull/1336, released in v1.23.0.
