### ISSUE TITLE
DefaultPKCEProvider challenge rejected 

### ISSUE THREAD

**Issue by sqrrrl** [googleapis/google-auth-library-java#1373]
#### Environment details

1. Meet (but not API-specific)
2. OS type and version: Linux
3. Java version: OpenJDK 17
4.  version(s):

#### Steps to reproduce

  1.  Create a UserAuthorizer with PKCE enabled
  2. Open authorization URL in browser

#### Code example

```java

      UserAuthorizer authorizer = UserAuthorizer.newBuilder()
          .setClientId(clientId)
          .setCallbackUri(callbackUri)
          .setScopes(SCOPES)
          .setPKCEProvider(new DefaultPKCEProvider())
          .build()
      URL authorizationUrl = authorizer.getAuthorizationUrl("me" "", null);
      System.out.printf("Open the following URL to authorize access: %s\n",
          authorizationUrl.toExternalForm());
```

#### Stack trace

None. Error is when attempting authorization, fails with error:

Access blocked: Authorization Error

Code Challenge must be base64 encoded. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2)

#### External references such as API reference guides

https://www.rfc-editor.org/rfc/rfc7636

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by sqrrrl** [comment]
Looks like the issue is padding. PKCE spec calls for having the padding stripped (https://www.rfc-editor.org/rfc/rfc7636#appendix-A) whereas the URL generated with the DefaultPkCEProvider has padding included (the trailing %3D in the challenge):

```
https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=1091545035118-1fgup6gnafl7fhneispbln4rt6olmb19.apps.googleusercontent.com&redirect_uri=http://localhost:38377/Callback&scope=https://www.googleapis.com/auth/meetings.space.created&state&access_type=offline&approval_prompt=force&login_hint=default&include_granted_scopes=true&code_challenge=Wv7S82_ZOSlisom9x4K_qljSAb0LTPSjUogEz8Aq08E%3D&code_challenge_method=S256
```

**Comment by sqrrrl** [comment]
And verified that removing the padding fixes the issues:

```
.setPKCEProvider(new DefaultPKCEProvider() {
  @Override
   public String getCodeChallenge() {
     return super.getCodeChallenge().split("=")[0];
   }
})
```

**Comment by TimurSadykov** [comment]
@clundin25 Could you please take a look, maybe applies to other langs?

**Comment by clundin25** [comment]
Thanks for pointing this out @sqrrrl ! I have opened https://github.com/googleapis/google-auth-library-java/pull/1375 to address this issue.
