### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.auth.CredentialTypeForMetrics | v1.28.0

### ISSUE THREAD

**Issue by lloydaf** [googleapis/google-auth-library-java#1527]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: MacOS Sequoia 15.0
3. Java version: 21
4.  version(s): 1.28.0

#### Steps to reproduce

  1. Use the version 1.28.0 in your `pom`
  2. Try to connect to a service (Google Drive in my case) and execute a  query

#### Code example

```kt
            val query = "mimeType = 'application/vnd.google-apps.folder'"
            val result: FileList = when (nextPageToken) {
                null -> buildSharedDrive()
                    .setQ(query)
                    .setFields("nextPageToken, files(id, name)")
                    .execute()
```

#### Stack trace
```
Caused by: java.io.IOException: Unexpected error refreshing access token
	at com.google.auth.oauth2.OAuth2Credentials.unwrapDirectFuture(OAuth2Credentials.java:325)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:183)
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadataForGdu(ServiceAccountCredentials.java:1038)
	at com.google.auth.oauth2.ServiceAccountCredentials.getRequestMetadata(ServiceAccountCredentials.java:1016)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:96)
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:91)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:565)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:506)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:616)
        at ...
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348)
	at ...
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146)
	... 78 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/google/auth/CredentialTypeForMetrics
	at com.google.auth.oauth2.ServiceAccountCredentials.getMetricsCredentialType(ServiceAccountCredentials.java:1024)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:512)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:270)
	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:267)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:635)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.auth.oauth2.OAuth2Credentials$AsyncRefreshResult.executeIfNew(OAuth2Credentials.java:582)
	at com.google.auth.oauth2.OAuth2Credentials.asyncFetch(OAuth2Credentials.java:233)
	... 98 common frames omitted
```

#### Any additional information below

It's a spring boot microservice using
```xml
        <dependency>
            <groupId>com.google.auth</groupId>
            <artifactId>google-auth-library-oauth2-http</artifactId>
            <version>1.28.0</version>
        </dependency>
```

**Comment by zhumin8** [comment]
This `CredentialTypeForMetrics` is a class newly introduced in [1.28.0](https://github.com/googleapis/google-auth-library-java/releases/tag/v1.28.0) for google-auth-library-credentials. 
You will also need to have 
```
        <dependency>
            <groupId>com.google.auth</groupId>
            <artifactId>google-auth-library-credentials</artifactId>
            <version>1.28.0</version>
        </dependency>
```

**Comment by zhumin8** [comment]
On second thought, `google-auth-library-oauth2-http:1.28.0` should bring in dependency `google-auth-library-credentials:1.28.0` by default. e.g.
```
[INFO] org.example:test:jar:1.0-SNAPSHOT
[INFO] \- com.google.auth:google-auth-library-oauth2-http:jar:1.28.0:compile
[INFO]    \- com.google.auth:google-auth-library-credentials:jar:1.28.0:compile

```
Are you overriding the `google-auth-library-credentials` version specifically? If not, can you share your dependency tree? I am curious where your project is getting the `google-auth-library-credentials` version from.

**Comment by MoritzHorch** [comment]
It seems that in our case spring-cloud-gcp and googlea-oi-services-sqladmin is still using 1.27.

![Screenshot 2024-10-22 at 08 12 18](https://github.com/user-attachments/assets/98a76839-0d50-4b8c-9766-03039531c8a6)

**Comment by lqiu96** [comment]
Could we see your Maven pom.xml or gradle file? I think it would be helpful if we could see the output of `mvn dependency:tree` or the gradle equivalent.

I believe the [latest version of spring-cloud-gcp](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases/tag/v3.8.10) is pulling in libraries-bom [v26.48.0](https://github.com/googleapis/java-cloud-bom/releases/tag/v26.48.0) which pulls in Auth-Library v1.27.0.

Until a new version of spring-cloud-gcp is released with the updated libraries-bom (v26.49.0), you may need to explicitly pull in v1.28.0 of the auth-library-http and auth-library-credentials

**Comment by zhumin8** [comment]
@MoritzHorch 
spring-cloud-gcp-starter will release a new version likely this week that ships with auth libraries v1.28.0.

Your screenshot is helpful. A few things I noticed:
- in your screenshot, there are both `google-auth-library-credentials` and `google-auth-library-oauth2-http` brought in by `goog-api-client` but with inconsistent versions. 
 <img src="https://github.com/user-attachments/assets/7d727758-1a58-40c6-9c0d-c9ec9cbc72ef" width="400"> 

- `mvn dependency:tree` shows 
for google-api-services-sqladmin
```
[INFO] \- com.google.apis:google-api-services-sqladmin:jar:v1-rev20241004-2.0.0:compile
[INFO]    \- com.google.api-client:google-api-client:jar:2.7.0:compile
[INFO]       +- com.google.auth:google-auth-library-credentials:jar:1.23.0:compile
[INFO]       \- com.google.auth:google-auth-library-oauth2-http:jar:1.23.0:compile
```
for spring-cloud-gcp-starter:
```
[INFO] \- com.google.cloud:spring-cloud-gcp-starter:jar:5.7.0:compile
[INFO]    \- com.google.cloud:spring-cloud-gcp-core:jar:5.7.0:compile
[INFO]       \- com.google.cloud:google-cloud-core:jar:2.44.1:compile
[INFO]          +- com.google.api:gax:jar:2.54.1:compile
[INFO]          +- com.google.auth:google-auth-library-credentials:jar:1.27.0:compile
[INFO]          \- com.google.auth:google-auth-library-oauth2-http:jar:1.27.0:compile

```
- In your pom file, are you specifying `google-auth-library-oauth2-http` version to 1.28.0? what about `google-auth-library-credentials` version? 
- Likely you need to specify versions for both of these if you choose to override.

**Comment by kessiler** [comment]
@zhumin8, I encountered an issue today where I was referencing only google-auth-library-oauth2-http. Based on your last note:

> On second thought, google-auth-library-oauth2-http:1.28.0 should bring in dependency google-auth-library-credentials:1.28.0 by default

This doesn’t seem to be the case.

**Comment by lqiu96** [comment]
@kessiler  Hmm, can we see your pom.xml or gradle file? There is a reference to the credentials module in the deps section of the pom.xml [here](https://github.com/googleapis/google-auth-library-java/blob/2761a39633a73bb93d36c097a854346091ee70fa/oauth2_http/pom.xml#L225-L228). I'm not sure why it wouldn't be bringing it in.

**Comment by kessiler** [comment]
Sure, here’s the pom.xml and the output from the mvn dependency:tree command. There’s a reference to the credentials module in the dependencies section, but it doesn't seem to be resolving as expected.


pom.xml:

<img width="638" alt="image" src="https://github.com/user-attachments/assets/913fd04d-ca98-4868-be81-8529192d98ae">

mvn dependency:tree:
<img width="771" alt="image" src="https://github.com/user-attachments/assets/976baae7-86e9-48c9-89a2-cdc2f2ad3c9e">

**Comment by lqiu96** [comment]
Can I see the full pom.xml so I can run the `mvn dependency:tree` locally?  `google-auth-library-credentials` may be brought in above if it's being omitted here.

Can you run `mvn dependency:tree -Dverbose` to see if it's being omitted? Or `mvn dependency:tree -Dincludes=com.google.auth:google-auth-library-credentials` to filter specifically for it?

**Comment by lqiu96** [comment]
This looks like `google-auth-library-credentials` is being pulled in by the kms jar. I'm guessing it's due to how the deps are ordered in the maven pom.xml file (`auth-credentials` is probably at the same depth for both kms and `auth-http`), so the first occurrence wins.

Can you try and use either the [libraries-bom](https://github.com/googleapis/java-cloud-bom/releases/tag/v26.49.0) (preferably) or [auth-bom](https://github.com/googleapis/google-auth-library-java/tree/main/bom) to manage these versions?

**Comment by kessiler** [comment]
I was already using libraries-bom for the KMS dependency, as shown below. Initially, I thought that adding google-auth-library-oauth2-http would bring in all necessary dependencies automatically:


```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>libraries-bom</artifactId>
            <version>26.48.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-kms</artifactId>
</dependency>
<dependency>
    <groupId>com.google.auth</groupId>
    <artifactId>google-auth-library-oauth2-http</artifactId>
    <version>1.28.0</version>
</dependency>
```

The simple fix turned out to be explicitly adding google-auth-library-credentials:
```

<dependency>
    <groupId>com.google.auth</groupId>
    <artifactId>google-auth-library-credentials</artifactId>
    <version>1.28.0</version>
</dependency>

```

Thank you!

**Comment by lqiu96** [comment]
Going to close this issue. Feel free to re-open if anything else comes up.

**Comment by tomaytotomato** [comment]
For me version upgrading to 9.4.3 doesn't include the class `FirebaseApp` 

So I used this exclusion to make 9.4.2 work

```
 <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-admin</artifactId>
      <version>9.4.2</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.auth</groupId>
          <artifactId>google-auth-library-oauth2-http</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.google.auth</groupId>
      <artifactId>google-auth-library-oauth2-http</artifactId>
      <version>1.19.0</version>
    </dependency>
```

**Comment by lqiu96** [comment]
> couldn't resolve FirebaseApp class

Could you provide a stacktrace for this? From looking at your exclusion, it seems similar to https://github.com/firebase/firebase-admin-java/issues/1045.

I'm guessing that you have a mismatch between the oauth2 and credentials modules.
