### ISSUE TITLE
How to suppress warning about Google Cloud SDK credentials?

### ISSUE THREAD

**Issue by lbergelson** [googleapis/google-auth-library-java#193]
I'm wondering how to suppress the warning:

```
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
```

Our application is a desktop application that uses the users default credentials to access files on the cloud and this warning is confusing to users.  Is there a way to suppress it?  I thought I'd found one but I accidentally asked in the php version of the auth library and not the java one.  

Would it be possible to port the patch that they implemented to suppress the warning when the environment variable `SUPPRESS_GCLOUD_CREDS_WARNING` is set to `true`?

https://github.com/googleapis/google-auth-library-php/pull/199#issuecomment-411490419

**Comment by chingor13** [comment]
There is currently not a way to suppress the warning. PHP has a unique situation where triggered warnings can make tests fail so we provided a mechanism to suppress the warning. We really advise using service accounts if it's a production application.

That said, we can take a look.

**Comment by lbergelson** [comment]
It's an application that users tend to run on their own laptops on their own files.  Getting them to set up a service account is a difficult undertaking.  We use service accounts in our large scale production setting with the same tools, but the personal account use is an important one.
