### ISSUE TITLE
Missing tag for 0.12.0 release

### ISSUE THREAD

**Issue by lbergelson** [googleapis/google-auth-library-java#215]
The last release tagged in github is 0.11.0, but there's a 0.12.0 tag in maven https://search.maven.org/artifact/com.google.auth/google-auth-library-parent/0.12.0/pom.  

Is it possible to add the 0.12.0 tag to github so that it's clear which commits are included?

**Comment by chingor13** [comment]
Whoops, we released and never merged the release commit/tag.

Available here: https://github.com/googleapis/google-auth-library-java/releases/tag/v0.12.0

**Comment by lbergelson** [comment]
@chingor13 Thank you!
