### ISSUE TITLE
DefaultCredentialsProvider is broken for java8 app engine 

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-auth-library-java#228]
This was reported by a bigtable customer:

> I've traced through where it fails. In DefaultCredentialsProvider.getDefaultCredentialsUnsynchronized() it will only return the AppEngine credentials if the following evaluates to true:
> 
>     this.isOnGAEStandard7()
> 
> I am on GAE Standard but am using Java 8 not 7, so this check is false and it does not return any valid credentials.

**Comment by sduskis** [comment]
If you look farther down, you'll see this:

```
    // Then try Compute Engine and GAE 8 standard environment
    if (credentials == null) {
      credentials = tryGetComputeCredentials(transportFactory);
    }
```

**Comment by sduskis** [comment]
@neozwu, do you have any thing to add to this issue?

**Comment by romulets** [comment]
I'm having the same problem. Although it falls in this condition the method `tryGetComputeCredentials` is also returning `null`.

I'm using AppEngine with Java 8

**Comment by sduskis** [comment]
@ajaaym, can you please have someone take a look at this?

**Comment by ajaaym** [comment]
@romulets can you please check whether you have this env variable set GCE_METADATA_HOST to "http://metadata.google.internal"? If not can you set that? In mean time I will create a PR to update default metadata url.

**Comment by romulets** [comment]
I didn't work :/

I configured the environment variable through `appengine-web.xml` using the following  tag:

```xml
    <env-variables>
        <env-var name ="GCE_METADATA_HOST" value="metadata.google.internal"/>
    </env-variables>
```
The host doesn't need the protocol because the code already attributes it automatically:

```java
  public static String getMetadataServerUrl(DefaultCredentialsProvider provider) {
    String metadataServerAddress = provider.getEnv(DefaultCredentialsProvider.GCE_METADATA_HOST_ENV_VAR);
    if (metadataServerAddress != null) {
      return "http://" + metadataServerAddress;
    }
    return DEFAULT_METADATA_SERVER_URL;
  }
```
The default metadadata server url is `http://169.254.169.254`

I'm still getting the error

```
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:119)
```

**Comment by ajaaym** [comment]
@romulets are you running on GCP?

**Comment by romulets** [comment]
Yes, AppEngine GCP

**Comment by ajaaym** [comment]
@romulets are you using flexible env?

**Comment by romulets** [comment]
@ajaaym No, I'm using standard environment, java8 runtime.

**Comment by ajaaym** [comment]
@romulets Thanks, I tried with standard java8 runtime and its working fine with me. Is it possible to provide the sample that you are using?

**Comment by romulets** [comment]
I'm retrieving a PubSub Publisher through this code:

```
        Credentials credentials = GoogleCredentials.getApplicationDefault();
        CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(credentials);

        return Publisher.newBuilder(topic)
                .setCredentialsProvider(credentialsProvider)
                .build();
```

**Comment by ajaaym** [comment]
@romulets I also used pubsub publisher. below is my code. You dont need to provide default credential client discovers that automatically.
```
ProjectTopicName topicName = ProjectTopicName.newBuilder()
        .setProject(ServiceOptions.getDefaultProjectId())
        .setTopic("topic-name")
        .build();
    Publisher publisher = Publisher.newBuilder(topicName).build();
    PubsubMessage pubsubMessage =
        PubsubMessage.newBuilder().setData(ByteString.copyFromUtf8("test message")).build();
```

**Comment by romulets** [comment]
@ajaaym I wasn't providing credentials and had the same error. I don't know if it is relevant, but my project runtime was java7 and then we migrated it to java8.

Anyway, I solved my problem by providing a hard-coded service account.

**Comment by ajaaym** [comment]
@romulets which version of pubsub are you using?

**Comment by romulets** [comment]
@ajaaym 0.33.0-beta

**Comment by ajaaym** [comment]
@romulets I tried with 0.33.0-beta and it worked fine. Below is my code:

Code:
```
    TopicName topicName = TopicName.newBuilder()
        .setProject(ServiceOptions.getDefaultProjectId())
        .setTopic("topic-name")
        .build();
    Publisher publisher = Publisher.newBuilder(topicName).build();
    PubsubMessage pubsubMessage =
        PubsubMessage.newBuilder().setData(ByteString.copyFromUtf8("test message")).build();
```

Printing all env variables gives me below output:
```
key: DATACENTER value: us16 
key: GCE_METADATA_HOST value: metadata.google.internal 
key: GAE_DEPLOYMENT_ID value: 416909112106027743 
key: GAE_APPLICATION value: s~grass-clump-479 
key: GOOGLE_CLOUD_PROJECT value: grass-clump-479 
key: GAE_SERVICE value: gae8-test 
key: GAE_ENV value: standard 
key: GAE_INSTANCE value: 00c61b117c05fa8a85f475d9a6ec02b941debd9b8b986c8e05ce8640e107477808809ca83a 
key: USER value: appengine 
key: TMPDIR value: /tmp 
key: GAE_VERSION value: gae8-test:20190320t144453 
key: GCLOUD_PROJECT value: grass-clump-479 
key: GAE_RUNTIME value: java8
```

**Comment by hugo-ayala** [comment]
I ended up using a hard coded service account as well. I don't have problems with other services like Cloud Storage or KMS, but PubSub was a nogo
