### ISSUE TITLE
Google Auth Library doesn't seem to completely implement the api it replaces in google-api-java-client on Google App Engine

### ISSUE THREAD

**Issue by mitcoding** [googleapis/google-auth-library-java#272]
I currently have an google app engine project that has been live for 5+ years now and working fine. 

I attempted to upgrade google-api-client-appengine from 1.28.0 to 1.29.2 today. And Found that GoogleCredential.getDefaultCredentials() was deprecated. So updated the code to use AppEngineCredentials.getApplicationDefault() in the google-auth-library as suggested in the deprecation comments and then passed the results into the new HttpCredentialsAdapter class so it would still work with urlFetchTransport.createRequestFactory in google-api-client-appengine per the answers I got in this thread [https://github.com/googleapis/google-api-java-client/pull/1261](https://github.com/googleapis/google-api-java-client/pull/1261) 

When I did that everything compiled but when I ran the same code in google app engine I now get this error at runtime

"Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."

This doesn't seem to be the expected behavior if this is supposed to be a one to one replacement of the GoogleCredential class now deprecated. So I was asked to post an issue here so more light could be shed on this issue and hopefully resolved.

**Comment by mitcoding** [comment]
Left out one part in the description above. I also first tried GoogleCredentials.getApplicationDefault() as that seemed that would have been closer to what GoogleCredential.getApplicationDefault() did. But then tried AppEngineCredentials.getApplicationDefault() since that was now available with the new API in case that made a difference. Both gave the same error listed above. 

With that said since nether works currently once we get  get one at least grabbing the default credentials I'm curious if I should be using the first one or the second one. As the end result for grabbing the google credential is to communicate with Google Firebase. Which like I said above works just fine using the legacy api that was just deprecated 17 days ago in the google client api.

**Comment by chingor13** [comment]
It looks like you're using the legacy AppEngine standard environment (i.e. not the Java 8 or 11 runtime). For that environment (which itself is deprecated), you'll want to use `AppEngineCredentials` from `com.google.auth:google-auth-library-appengine`. This artifact depends upon the AppEngine SDK.

```java
import com.google.auth.oauth2.GoogleCredentials;
import com.google.auth.appengine.AppEngineCredentials;

GoogleCredentials credentials = 
    AppEngineCredentials.newBuilder()
        .setScopes(...)
        .setAppIdentityService(serviceFromSdk)
        .build();
```
Note that the base `google-auth-library-oauth2-http` artifact provides a different `AppEngineCredentials` but that is for the newer Java 8/11 AppEngine environments.

**Comment by mitcoding** [comment]
@chingor13 Is there something on google's servers that says I'm using the legacy standard app engine environment? Because, as far as I know I'm using the newest Java8/11 App Engine Environment  as I'm compiling with Java 8 and the appengine-web.xml runtime config element has been set to use java 8 for the last two years since Google made it fully available in 2017.

On another note, when I logged into github several days ago on my phone (as I was away from the office), I got a notification, that was only ever seen on my phone, that pointed me to some old closed issues here that might be the reason this library isn't a true one to one replacement for the old GoogleCredential.getDefaultCredentials() from google-api-client-appengine, and would suggest that GoogleCredential.getDefaultCredentials() from google-api-client-appengine shouldn't be deprecated yet if the answer is still true for this library.

[An error getting default credentials on GAE Standard / Java8 with urlfetch](https://github.com/googleapis/google-auth-library-java/issues/191)

As mentioned above I specifically set java8 in the runtime config. But since I migrated from java 7 to java 8 two years ago I specifically set the url-stream-handler to use urlfetch, because the company I maintain this app for didn't want the increased costs of the using the native http protocols and wanted to hold onto the cheaper pricing offered through urlFetch. According to your answer in the link above it sounds like this library doesn't work with urlFetch and that is by design. If that is still true then I would argue that by deprecating GoogleCredential.getDefaultCredentials() in google-api-client-appengine and not supporting urlFetch in this new library you are also deprecating the use of urlFetch on java 8/11 Appengine environments. This seems pre-mature since I'm not aware of google publicly saying anything about deprecating urlFetch as a configuration setting in java 8/11 App Engine any time soon.

**Comment by chingor13** [comment]
Does the AppEngineCredentials implementation using AppIdentityService work for you?

**Comment by mitcoding** [comment]
@chingor13 so using:

GoogleCredentials credentials = 
    AppEngineCredentials.newBuilder()
        .setScopes(...)
        .setAppIdentityService(AppIdentityServiceFactory.getAppIdentityService() )
        .build();

Is what fixed the issue. With that said is there a reason why AppEngineCredentials.getApplicationDefault().createScoped(...) 

doesn't work the same way as

 AppEngineCredentials.newBuilder()
        .setScopes(...)
        .setAppIdentityService(AppIdentityServiceFactory.getAppIdentityService() )
        .build();

**Comment by chingor13** [comment]
The `getApplicationDefault()` is inherited from the base `GoogleCredentials` which tries to do the detection from environment variables and assumes you are using credentials provided from the environment or are in an environment that can talk to the GCE metadata server.

That method probably belongs elsewhere but in anycase, we should override it in  `com.google.auth.appengine.AppEngineCredentials` to either try to do the detection or to fail with a better error message.

**Comment by chingor13** [comment]
We added a deprecation warning and logging if you try to use `com.google.auth.appengine.AppEngineCredentials.getApplicationDefault()`
