### ISSUE TITLE
Can't pass scopes to GoogleCredentials

### ISSUE THREAD

**Issue by varelasavela** [googleapis/google-auth-library-java#299]
#### Environment details

- OS: Mac
- Java version: 11
- google-auth-library-java version(s): 0.12.0

#### Steps to reproduce
I am trying to use default google credentials and pass them scopes:
GoogleCredentials applicationDefault = GoogleCredentials.getApplicationDefault().createScoped(scopes);

I see that the implementation of createScoped method is :

```java
 /**
   * If the credentials support scopes, creates a copy of the the identity with the specified
   * scopes; otherwise, returns the same instance.
   *
   * @param scopes Collection of scopes to request.
   * @return GoogleCredentials with requested scopes.
   */
  public GoogleCredentials createScoped(Collection<String> scopes) {
    return this;
  }
```
As you can see , nothing done with parameter scopes.

**Comment by chingor13** [comment]
`GoogleCredentials` is the base class for many of the other credential types. When you call `GoogleCredentials.getApplicationDefault()`, the code attempts to build credentials depending upon the execution environment. `GoogleCredentials.getApplicationDefault()` could return you any of:
* `AppEngineCredentials`
* `CloudShellCredentials`
* `ComputeEngineCredentials`
* `ServiceAccountCredentials`
* potentially new ones in the future

All of these extend from `GoogleCredentials` and most/all of them implement `createScoped()`
