### ISSUE TITLE
JWT token + getRequestMetadata(entry point)

### ISSUE THREAD

**Issue by ejona86** [googleapis/google-auth-library-java#30]
`Credentials.getRequestMetadata(URI)` is passed a URI defined as "the entry point for the request". What does that mean?

To be in sync with grpc/grpc#2911 and work with the current `ServiceAccountJwtAccessCredentials`, the URI passed would need to exclude the gRPC method name. But given the credential API, I would more expect the URI to be the request URI, which would include the method name.

Is it possible for "entry point" to be better defined?

**Comment by anthmgoogle** [comment]
Yes, I've been thinking about what we should do here. In the short run the Java library just passes the URI straight through as the Audience with no processing. 

What I think we should do here:
- Have the transport pass in the full URI of the method call.
- Have the ServiceAccountJwtAccessCredentials trim this down the just the entry point to use as the Audience field.

The thinking is that while Jwt Access Credentials does not happen to use the method, a theoretical credential might. Also, the Jwt Accses Credential probably needs some caching, so it needs to truncate this as a key for the caching as well.

We should discuss with other implementers of the auth libraries. If this is the way to go, we should implement the truncation in the auth library first. When that version is consumed by grpc-java, the truncation can be removed from that layer.

**Comment by garrettjonesgoogle** [comment]
Is this a breaking change?
