### ISSUE TITLE
IllegalArgumentException using IdTokenCredentials in GKE

### ISSUE THREAD

**Issue by RolT** [googleapis/google-auth-library-java#340]
#### Environment details

- GKE: v1.13.7-gke.8
- OS: Linux 4.14.127+
- Java version: 1.8.0_181
- google-auth-library-java version(s): 0.17.1

#### Steps to reproduce

1. Use workload identity in GKE
2. Get google credentials from application default
3. Generate `IDTokenCredentials` from the google credentials and set the target audience
4. Call refresh on the `IDTokenCredentials`

#### Stacktrace

```
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:35)
	at com.google.api.client.json.webtoken.JsonWebSignature$Parser.parse(JsonWebSignature.java:559)
	at com.google.api.client.json.webtoken.JsonWebSignature.parse(JsonWebSignature.java:494)
	at com.google.auth.oauth2.IdToken.create(IdToken.java:82)
	at com.google.auth.oauth2.IdToken.create(IdToken.java:70)
	at com.google.auth.oauth2.ComputeEngineCredentials.idTokenWithAudience(ComputeEngineCredentials.java:199)
	at com.google.auth.oauth2.IdTokenCredentials.refreshAccessToken(IdTokenCredentials.java:121)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:157)
```

#### Code snippet

```clojure
(import [com.google.auth.oauth2 IdTokenCredentials AccessToken GoogleCredentials])

(let [target-audience "https://my-cloud-run-app.run.app"
      ^GoogleCredentials credentials (GoogleCredentials/getApplicationDefault)
      token-credentials (-> (IdTokenCredentials/newBuilder)
                            (.setIdTokenProvider credentials)
                            (.setTargetAudience target-audience)
                            (.build))]
  (.refresh token-credentials))
```

I can provide a groovy version if needed.

#### Any additional information below

It works locally using my default credentials, but not on GKE. The main difference I see is that on GKE it will use `ComputeEngineCredentials`. The error is quite uninformative so I don't know if it is an access problem on my side or a bug.

Thanks

**Comment by RolT** [comment]
The groovy version:

```groovy
@Grapes([
    @Grab(group='com.google.auth', module='google-auth-library-oauth2-http', version='0.17.1')
  ])

import com.google.auth.oauth2.IdTokenCredentials
import com.google.auth.oauth2.GoogleCredentials

def googleCredentials = GoogleCredentials.getApplicationDefault()
def idTokenCredentials = IdTokenCredentials.newBuilder()
  .setIdTokenProvider(googleCredentials)
  .setTargetAudience('https://my-cloud-run-app.run.app')
  .build()

idTokenCredentials.refresh()
```

Note that `googleCredentials` work correctly, only the `idTokenCredentials` don't. I tried to play with the different `IdTokenProvider.Option` but it does not help.

**Comment by RolT** [comment]
Hello,

I did a bit of digging and the value of the token here https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L198 is `"GKE Metadata Server encountered an error: Not Found\n"`

Document url is: "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=https://my-cloud-run-app.run.app"

Could it be that it does not find my cloud run service ? The service is deployed on the managed Cloud Run (not our GKE instance). Should I move the issue somewhere else ?

In any case it's probably worth it to handle the actual error here.

```clojure
(import com.google.api.client.http.GenericUrl)
(import com.google.auth.oauth2.ComputeEngineCredentials)
(def documentUrl (GenericUrl. (ComputeEngineCredentials/getIdentityDocumentUrl)))
(.set documentUrl "audience" "https://my-cloud-run-app.run.app")
(defn call-method
  [klass method-name params obj & args]
  (-> klass (.getDeclaredMethod (name method-name)
                                (into-array Class params))
      (doto (.setAccessible true))
      (.invoke obj (into-array Object args))))
(def response (call-method ComputeEngineCredentials 'ComputeEngineCredentials/getMetadataResponse [String] credentials (.toString documentUrl)))
(.parseAsString response)
```

**Comment by RolT** [comment]
It is a confirmed bug in GKE, I'm closing the issue, but I still think we could have a better error message here.

**Comment by davidxia** [comment]
Thanks for creating this issue. Is there a fix for this planned or somewhere we can track the progress on this bug?

**Comment by RolT** [comment]
Hello,
I filed an issue here: https://issuetracker.google.com/issues/140709355
and there is a duplicate here: https://issuetracker.google.com/issues/140884260
No ETA at the moment...
