### ISSUE TITLE
Why is JwtClaims.newBuilder() package private?

### ISSUE THREAD

**Issue by bastova** [googleapis/google-auth-library-java#349]
I am trying to override the audience with my custom audience claim. I found the method jwtWithClaims in ServiceAccountJwtAccessCredentials. But this method seems useless because I can't actually create any JwtClaims since the builder is not accessible from outside package.

#### Environment details

- OS: any
- Java version: 1.8
- google-auth-library-java version(s): 0.17.1

#### Steps to reproduce

Credentials credentials = ServiceAccountJwtAccessCredentials.fromStream(credsStream, URI.create(AUDIENCE)).jwtWithClaims(???);

How do I pass a JwtClaim into the ??? Or am I doing this wrong?

#### Stacktrace

```
Any relevant stacktrace here.
```

#### Code snippet

```java
// I want to put something like 
Credentials credentials = ServiceAccountJwtAccessCredentials.fromStream(credsStream, URI.create(AUDIENCE)).jwtWithClaims(JwtClaims.newBuilder().withAudience(AUDIENCE).build());
```

#### External references such as API reference guides used

- ?

#### Any additional information below

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chingor13** [comment]
You're right, it should be public. We will fix and get a new version published.
