### ISSUE TITLE
I can't access on the Google Tag Manager with GoogleCredentials

### ISSUE THREAD

**Issue by aaschlote** [googleapis/google-auth-library-java#373]
Hi,

I'm making a project, where I should get some informations in the Google Tag Manager. I'm using the API TagManager and using the library GoogleCredentials. But I've received the the following error:

`{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Not found or permission denied.",
    "reason" : "notFound"
  } ],
  "message" : "Not found or permission denied.",
  "status" : "NOT_FOUND"
}
`

About the configurations I did the follow steps:

1 - Created a "Service account keys" on the Google API (Credentials)
2 - Downloaded the JSON  credentials
3 - Developed the below code:

`
try {
            String accountId = "XXXXXX";
            String secretsLocation = "API-KEY.json";
            HttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
            JacksonFactory jsonFactory = JacksonFactory.getDefaultInstance();

            FileInputStream fileInputStream = new FileInputStream(secretsLocation);

            GoogleCredentials credential = GoogleCredentials.fromStream(fileInputStream);
            credential = credential.createScoped("https://www.googleapis.com/auth/tagmanager.readonly","https://www.googleapis.com/auth/tagmanager.edit.containers");

            AccessToken token = credential.refreshAccessToken();
            System.out.println(token.getTokenValue());

            HttpRequestInitializer initializer = new HttpCredentialsAdapter(credential);

            TagManager manager = new TagManager.Builder(httpTransport, jsonFactory,initializer).setApplicationName("MSX").
                    setServicePath("tagmanager/v2/accounts").build();

            for (Container container : manager.accounts().containers().list(accountId).execute().getContainer()) {
                System.out.println(container.getPublicId());
            }
        }catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }

`

Can you guys help me about this problem? I didn't find any example using the library GoogleCredentials and API TagManager. In Google website API just shows examples with old versions or in Python and JavaScript (https://developers.google.com/tag-manager/api/v2/devguide)

Thanks in advance!
Alex

**Comment by jashwanth9845** [comment]
> I forgot to do a configuration on the Google Tag Manager and now it's working.
> 
> But I would be nice if it has more examples with this new library on the Google Developer API.
> 
> Best Alex August Schlote

can you explain what configuration on the Google Tag Manager you made..? because i am facing the same issue
