### ISSUE TITLE
Support scoped credentials for metadata-based credentials

### ISSUE THREAD

**Issue by sqrrrl** [googleapis/google-auth-library-java#381]
The metadata service for GCP (at least on appengine/gcf/cloud run) allows fetching scoped tokens. This has been implemented in some of the auth clients already (node, go, PR pending for python), but missing from Java and possibly some others.

https://cloud.google.com/functions/docs/securing/function-identity#access_tokens describes how it works.

**Comment by westarle** [comment]
I think it's fixed in #514
