### ISSUE TITLE
401 unauthorized issue when calling refreshing Access Token

### ISSUE THREAD

**Issue by douglassu** [googleapis/google-auth-library-java#404]
I'm trying to send email using my Gmail API from my server-side service.  I have configured a Service Account credential and enabled domain wide delegation for the service.  

```
Resource resource = new ClassPathResource("thematic-acumen-266302-09937adda039.properties");
sourceCredentials = (ServiceAccountCredentials)sourceCredentials.createDelegated("me@myemail.com");
ServiceAccountCredentials sourceCredentials = ServiceAccountCredentials
        	     		.fromStream(resource.getInputStream());
sourceCredentials = (ServiceAccountCredentials) sourceCredentials
        				.createScoped(GmailScopes.all());
AccessToken token =sourceCredentials.refreshAccessToken();
```
The credential.json file is renamed into a .properties file so I can use Spring's built-in Resource to load the file.  The credentials seems to be loaded properly.
The code snippet above will produce the following issue when the refreshAccessToken gets called:
```
java.io.IOException: Error getting access token for service account: 401 Unauthorized
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:444)
```
If I remove the following from the code snippet:
```
sourceCredentials = (ServiceAccountCredentials)sourceCredentials.createDelegated("me@myemail.com");

```
The refreshAccessToken will work and my Gmail API request will send out but in return receive the following response:

```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Bad Request",
    "reason" : "failedPrecondition"
  } ],
  "message" : "Bad Request"
}

```
 #### Environment details

- OS: Mac OSX 10.15.1
- Java version: 1.8.0_112
- google-auth-library-java version(s): google-auth-library-oauth2-http version: 0.20.0

Please help.  
Thanks!

**Comment by douglassu** [comment]
I found the answer to my problem based on this thread after searching around:

https://stackoverflow.com/questions/29760949/400-bad-request-on-gmail-api-with-php?rq=1

"You should not be using a service account if you just want to access one account (your own). Service accounts are their own account and they're not Gmail accounts. They work well for APIs that don't need a user (e.g. maps, search) or when you are using a Google Apps for Work domain and want delegation enabled for all users in the domain (by domain admin, so you don't need individual user authorization)."

I have modified my implementation to use oauth web auth flow now.  I'm really disappointed on Google's documentation as this matter should be addressed outright and as concise as possible.  I'm sure "Service Account" and "domain wide delegation" mis-led many developers to use the Service Account approach for many types of personal/individual account application.

**Comment by asdkalluri** [comment]
I'm noticing the same 401 error but it is intermittent for me which makes it worse. I'm using the Calendar API though

**Comment by khatwaniNikhil** [comment]
@douglassu thanks, you got the issue fixed as per quote  "I have modified my implementation to use oauth web auth flow now."
