### ISSUE TITLE
404 Error when getting access token for Impersonated Credentials

### ISSUE THREAD

**Issue by KateHamster** [googleapis/google-auth-library-java#406]
Hello,

I am trying to impersonate a normal user with the service account and to get the access token in order to access with the service account the normal users mails. We have given the wide authority delegation and we have added this role to the service account roles:
iam.serviceAccountTokenCreator. However, my small function is not working. After putting System.out.println everywhere I have found that the error is generated by this line:
targetCredentials.refreshAccessToken();

The error message is the following:

```
Java.io.IOException: Error requesting access token
Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found
{
"error": {
"code": 404,
"message": "Requested entity was not found.",
"errors": [
{
"message": "Requested entity was not found.",
"domain": "global",
"reason": "notFound"
}
],
"status": "NOT_FOUND"
}
}
```

#### Environment details

OS: Windows 10
Java version: jre 1.8.0_131
google-auth-library-java version(s): 0.20
list of included jars:
![image](https://user-images.githubusercontent.com/11301284/73828287-43ed1700-4801-11ea-8f1f-b5c3dc08d5e9.png)

#### Stacktrace

```
java.io.IOException: Error requesting access token
	at com.google.auth.oauth2.ImpersonatedCredentials.refreshAccessToken(ImpersonatedCredentials.java:261)
	at routines.GoogleCredentialSA.getTokenImpersonate(GoogleCredentialSA.java:28)
Caused by: com.google.api.client.http.HttpResponseException: 404 Not Found
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "errors": [
      {
        "message": "Requested entity was not found.",
        "domain": "global",
        "reason": "notFound"
      }
    ],
    "status": "NOT_FOUND"
  }
}

	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1094)
	at com.google.auth.oauth2.ImpersonatedCredentials.refreshAccessToken(ImpersonatedCredentials.java:259)
	... 14 more
```

#### Code snippet

```java
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Arrays;

import com.google.auth.oauth2.AccessToken;
import com.google.auth.oauth2.ImpersonatedCredentials;
import com.google.auth.oauth2.ServiceAccountCredentials;
	
	
	
public class GoogleCredentialSA {
	public static String getTokenImpersonate(String emailAddress, String fileAddress, String scope) {
	    	
	    String credPath = fileAddress;
	    ServiceAccountCredentials sourceCredentials;
		try {
			
			sourceCredentials = ServiceAccountCredentials.fromStream(new FileInputStream(credPath));
			sourceCredentials = (ServiceAccountCredentials) sourceCredentials.createScoped(Arrays.asList(scope));
			ImpersonatedCredentials targetCredentials = ImpersonatedCredentials.create(sourceCredentials,
		    			emailAddress, null,Arrays.asList(scope), 3600);
			
			targetCredentials.refreshAccessToken();
			
			AccessToken token = targetCredentials.getAccessToken();
			
			String token2 = token.getTokenValue();
			
			return token2;
	
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	    	
	    return "";
	}
}
```

I don't really understand what is not found the token?
Is the impersonated credentials actually supports the token generation?
Thank you!

**Comment by chingor13** [comment]
For your use case, the underlying API call invoked is [project.serviceAccounts/generateAccessToken](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/generateAccessToken). The missing identity could possibly be the email address of the `targetPrincipal` (either non-existent or a permissions issue).

cc @salrashid123 who may know more about domain-wide delegation and impersonated credentials.

**Comment by salrashid123** [comment]
I dont' think domain-wide delegation can be set by requesting just an `access_token` with that endpoint.  DWD sets the `sub` field in a signed JWT that gets exchanged (the `generateAccessToken()` for impersonated attempts to impersonate a service account (not service account as a gsuites user).

---

i wroteup a a credential type that does do domain delegation and uses the source credentials to sign:
`DomainDelegatedCredentials.java`: here to `sign`:
   - https://gist.github.com/salrashid123/4d0325743d5717c19ad5ae558f381792#file-domaindelegatedcredentials-java-L84

Usage here:
   https://gist.github.com/salrashid123/9b1013b8c010ac45530cd0e47c28f39b

Now, thats just a hack...service account credentials  currently allows for [createDelegated()](https://googleapis.dev/java/google-auth-library/latest/com/google/auth/oauth2/ServiceAccountCredentials.html#createDelegated-java.lang.String-)  which is actually the right implementation 


I'd imagine the IAMCredetnials will use the `signBlob()` API call internally when called when it implements `createDelegated()`... 

I guess what i'm trying to say is the hack cited above will work for any credential type but the better way is to implement createdelegated into impersonatedcredetnials.


the golang variation is:
  https://github.com/salrashid123/oauth2#impersonated-credentials-with-domain-wide-delegation

**Comment by salrashid123** [comment]
wait... @KateHamster  ...in rereading, i dont' think you're even after impersonated credentials here.

its a nuance but your'e after domainwide delegation in java  (in the snippet below, the service account file has dwd capabilities and the `sub` field in `createddelegates()` is what you're going to act as .

```java
           File credentialsPath = new File(keyFile);
            try (FileInputStream serviceAccountStream = new FileInputStream(credentialsPath)) {
                sourceCredentials = ServiceAccountCredentials.fromStream(serviceAccountStream);
            }

            String sub = "admin@yourdomain.com";
            List<String> scopes = new ArrayList<String>();
            scopes.add("https://www.googleapis.com/auth/admin.directory.user");
            scopes.add("https://www.googleapis.com/auth/admin.directory.group");            
            sourceCredentials = sourceCredentials.createScoped(scopes);
            sourceCredentials = sourceCredentials.createDelegated(sub);

// now use sourceCredentials 
```

**Comment by KateHamster** [comment]
@salrashid123 , thank you for your feedback.
I was not trying to set the domain-wide delegation for the service account, it was done in the gcp project, in which the service account was created. We have added this scope "https://www.googleapis.com/auth/admin.directory.user" for the service account, I will ask our GCP admin to add this scope "https://www.googleapis.com/auth/admin.directory.group" via his admin platform. 

If all the scopes are parametrized on the platform, should I still a domain wide delegation via Java (if it has been already done via the Google Cloud platform).

My final goal is to just access user mails and Google drive using a service account, so I was supposing that it is an impersonation, isn't it? Or I should do something else for accessing with service account user mails and drive?

**Comment by salrashid123** [comment]
* `ImpersonatedCredentials.java` here is [user or serviceaccountA]  assuming the identity of [serviceaccountB] 

* in gsuites, a service account can impersonate another user (you do that part by not using `ImpersonatedCredentials.java` here but using the `createDelegate()`  method and then using those credentials to access the mail/calendar api.   (

in the follwoing, the service acocunt has domain delegation rights.  Once those creds are initialized, you signify the user to assume by setting the `createdelegate()` parameter

from there, you use the gmail api 

```java
package com.test;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.List;

import com.google.api.client.http.HttpRequestInitializer;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.jackson2.JacksonFactory;
import com.google.api.services.gmail.Gmail;
import com.google.api.services.gmail.GmailScopes;
import com.google.api.services.gmail.model.ListMessagesResponse;
import com.google.api.services.gmail.model.Message;
import com.google.auth.http.HttpCredentialsAdapter;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.auth.oauth2.ServiceAccountCredentials;

public class TestApp {

	public static void main(String[] args) {
		TestApp tc = new TestApp();
	}

	public TestApp() {
		try {

			String keyFile = "/home/srashid/gcp_misc/certs/google_apps_svc_dwd.json";

			GoogleCredentials sourceCredentials;

			File credentialsPath = new File(keyFile);
			try (FileInputStream serviceAccountStream = new FileInputStream(credentialsPath)) {
				sourceCredentials = ServiceAccountCredentials.fromStream(serviceAccountStream);
			}

			String someuser = "user10@esodemoapp2.com";

			List<String> scopes = new ArrayList<String>();
			scopes.add(GmailScopes.GMAIL_READONLY);

			sourceCredentials = sourceCredentials.createScoped(scopes);
			sourceCredentials = sourceCredentials.createDelegated(someuser);
			HttpRequestInitializer requestInitializer = new HttpCredentialsAdapter(sourceCredentials);

			Gmail mservice = new Gmail.Builder(new NetHttpTransport(), JacksonFactory.getDefaultInstance(),
					requestInitializer).setApplicationName("foo").build();

			ListMessagesResponse response = mservice.users().messages().list(someuser).execute();
			for (Message message : response.getMessages()) {
				System.out.println(message.toPrettyString());
			}

		} catch (Exception ex) {
			System.out.println("Error:  " + ex);
		}
	}

}

```

all that gives me the output of the list of emails this user has (2, to be exact)

```
{
  "id" : "16ce2ecac55eb940",
  "threadId" : "16ce2ecac55eb940"
}
{
  "id" : "16ce2ecaab6a0e41",
  "threadId" : "16ce2ecaab6a0e41"
}
```

**Comment by KateHamster** [comment]
@salrashid123 Thank you! I am not getting the 404 no more!

**Comment by KateHamster** [comment]
@salrashid123 I have only one small question. Actually, what is the best practice:
- Use clientId and clientSecret parametrized for the user in the GCP project to get an accesToken?
Or
- To impersonate user via service account to get an Access Token?

P.S. I have not used the part of the gmail library usage, I acknowledge that this is the best way, but due to the specificity of the app, I am working in (Talend) I need only an access token for the further interraction with APIs via HTTP requests.

Thank you again for your help!

**Comment by salrashid123** [comment]
the clientid/secret is normal oauth2 flow (you'd ask a user for their consent and then proceed to access their email;  the email scope is a [sensitive scope](https://developers.google.com/gmail/api/auth/scopes)  and usually for oauth client's.  you'd also have to keep track of clientid/s and their refresh tokens.   the domain delegation with svc accounts maybe just easier here.

anyway, here's an [article about java+dwd](https://medium.com/@salmaan.rashid/easy-gsuites-domain-wide-delegation-dwd-in-java-5abc7d08f1e1)

**Comment by fdbatista** [comment]
@KateHamster @salrashid123  Hi, people. I landed here with a very similar problem, but when I try to run the fragment of code @salrashid123 posted, I get an `java.io.IOException: Error requesting access token`. The only thing I am changing is the route the credentials file and the email address of `someuser`. Any ideas why this might be happening?

**Comment by salrashid123** [comment]
maybe check if the service account youre using using is authorized for domain delegation in gsuites
https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority

**Comment by fdbatista** [comment]
Domain-wide delegation was fine. Looks like the issue was related with the scopes. Thanks!

**Comment by ashish-blusynergy-dev** [comment]
Hi @salrashid123  I have used your code and made changes in just the json and the code change is like 

`File credentialsPath = new File(keyFile);
			FileInputStream serviceAccountStream = new FileInputStream(credentialsPath)
            sourceCredentials = ServiceAccountCredentials.fromStream(serviceAccountStream);
            String sub = "admin@abc.com";

            List<String> scopes = new ArrayList<String>();
            scopes.add(ResellerScopes.APPS_ORDER);
            scopes.add(SiteVerificationScopes.SITEVERIFICATION);
            scopes.add(DirectoryScopes.ADMIN_DIRECTORY_USER)

            sourceCredentials = DomainDelegatedCredentials.create(sourceCredentials, sub, scopes);

            HttpRequestInitializer requestInitializer = new HttpCredentialsAdapter(sourceCredentials);

            Reseller resellerService = new Reseller.Builder(new NetHttpTransport(),
                    JacksonFactory.getDefaultInstance(),
                    requestInitializer).setApplicationName("ResellerGCP").build()
           resellerService.customers().get("abc.com").execute()`

with this I am getting 403 forbidden error when i am doing a get customer call.

in the logs i can see access token gets created.  in postman when i do a get call with the access token it fails with same error 
but in api explorer its working.

**Comment by salrashid123** [comment]
@ashish-blusynergy-dev 

`domaindelegatedcredentials` isn not part of this repo  (its just a wrapper i wrote for the various underlying credential types).


if your'e using serviceaccounts (and not the  two step impersonation) , you can probably just use the direct snippet 
https://github.com/googleapis/google-auth-library-java/issues/406#issuecomment-583098985  or from the [official docs](https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account)

probably should verify if the user  your'e accessing the "reseller" api has the correct permission on thier own and if the service account is allowed for those scopes.


finally, just note you dn't need to use domain delegation anymore (i.,e svc account acting as a user and as that user access wrokspace apis....

with https://workspaceupdates.googleblog.com/2020/08/use-service-accounts-google-groups-without-domain-wide-delegation.html   you can use a service accoun directly

**Comment by ashish-blusynergy-dev** [comment]
Thanks for the help, Its still not working, as suggested.. 

My aim was to use service account and that internally will take care of the access token ( and refreshing it). 
With the code you have suggested it seems 95% of the work is done. some where some class is incorrect or scope or the GCP or permissions. 
Could you help me on this... right now I have created Ouath2 client id and working with that.. but I want to implement the other one.
