### ISSUE TITLE
Lack of any logging or debugging flags to assist in troubleshooting

### ISSUE THREAD

**Issue by lindsayismith** [googleapis/google-auth-library-java#430]
This plugin goes through a number of steps to try to find credentials. But there's no logging or any way to debug which of the methods was tried, which were unsuccessful, and whether any credentials were returned.  I'm trying to work out if my env var is even being seen by this plugin, but there's no way to tell.

**Comment by danoscarmike** [comment]
@lindsayismith what is your env var name and the nature of your credentials?

`export GOOGLE_APPLICATION_CREDENTIALS='<path to your service account credentials json>'` should do the trick. See https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable for more on this set up.

**Comment by lindsayismith** [comment]
Hi Dan,

My issue is specifically around the level of logging in this library, not a specific situation. My case is that I'm working on a Maven wagon that handles auth against my teams GCP service (https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools), and our library depends on this one to get application default credentials.

I've been testing the scenario where a maven project is built and deployed from Jenkins using our Wagon. I've been trying to work out how our plugin behaves in different situations and what the right way to set ADC should be as we write guides to our customers.  Because the build is running within Jenkins, it's tricky to introspect how that build is run, and what the env variables are, what the system path is, etc, etc.

Because this library has a number of different paths it might take to find ADC, I think it would be very useful, not just for me, but for any customer trying to debug their credential exchange, if there was logging in this library that can explain which steps it has tried and which it settled on. In particular the DefaultCredentialsProvider.java class implements the search strategy, but doesn't give any logging about what steps it is trying or which succeeds.

**Comment by danoscarmike** [comment]
Ah, OK. Let me investigate some more internally.
