### ISSUE TITLE
Anonymous Authentication (Against a Local Endpoint)

### ISSUE THREAD

**Issue by paualarco** [googleapis/google-auth-library-java#449]
Hello! 

I have been digging in how to connect from my java app to a local _docker image_ containing a GCS emulator, there are some examples in Python that uses AnonymousCredentials and I would like to know if there is something similar to that in java.

This is the ticket where python free credentials was introduced: https://github.com/googleapis/google-auth-library-python/pull/206 

And that would be a code example: https://github.com/fsouza/fake-gcs-server/blob/main/examples/python/python.py

Sorry if the question is too generic,

**Comment by ewjmulder** [comment]
@paualarco (and future people who stumble upon this on Google):
You can use the NoCredentialsProvider and/or NoCredentials classes to signal not using any credentials
