### ISSUE TITLE
Id Token vs Access Token

### ISSUE THREAD

**Issue by averikitsch** [googleapis/google-auth-library-java#450]
[IdTokenCredentials](https://googleapis.dev/java/google-auth-library/latest/com/google/auth/oauth2/IdTokenCredentials.html) provides a Google Issued OpenIdConnect token. The docs show getting a token using: `tokenCredential.getIdToken().getTokenValue();`. However in practice, `tokenCredential.getIdToken()` is null while `tokenCredential.refreshAccessToken().getTokenValue()` returns the ID token as an `AccessToken` object. Though based on https://github.com/googleapis/google-auth-library-java/issues/157 that seems planned.

Expected:
To get IdToken string from `tokenCredential.getIdToken().getTokenValue()`
To get an AccessToken string from `tokenCredential.refreshAccessToken().getTokenValue()`

Even though this is expected, I see that Id Token is a subclass of Access Token which depends on the type of credentials; therefore this isn't incorrect. However; why don't both work? and why do we have to call refresh to get the token?

**Comment by chingor13** [comment]
The design for all `Credential` types is that they are metadata providers where the actual auth token is lazy fetched. For the most part, a library should only care about interacting with the `Credentials` interface - it doesn't matter who provides the tokens. For most of our client libraries, you provide a configured (or autodetected) `Credentials` implementation and the actual token fetch (or refresh) happens as you call your endpoint.

You should never have to ask a `Credential` for it's token value to call our libraries (although you can). If you do, you will need to explicitly tell the credentials to refresh (or fetch the first time).

**Comment by averikitsch** [comment]
Great, thanks Jeff!
