### ISSUE TITLE
Incorrect license on Token verifier

### ISSUE THREAD

**Issue by rafaelmenta** [googleapis/google-auth-library-java#460]
TokenVerifier class and its test class both have the Apache license instead of BSD 3

## Environment details

N/A

#### Steps to reproduce

https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/TokenVerifier.java

https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/javatests/com/google/auth/oauth2/TokenVerifierTest.java

#### Stacktrace

N/A

#### Code snippet

N/A

#### External references such as API reference guides used

N/A

#### Any additional information below

N/A

**Comment by chingor13** [comment]
Fixed in #461
