### ISSUE TITLE
google-auth-library-oauth2-http has a hardcoded dependency on FasterXML Jackson2

### ISSUE THREAD

**Issue by medb** [googleapis/google-auth-library-java#512]
If I want to get rid of Jackson2 in my application it's impossible because `google-auth-library-oauth2-http` has a hard dependency on it.

Other Google API client libraries either require caller to supply `JsonFactory` instance (which could be  `JacksonFactory` or `GsonFactory`) during initialization or have 2 artifacts with Gson and Jackson dependencies:  `-gson` and `-jackson2`.

**Comment by chingor13** [comment]
Allowing the developer to supply a `JsonFactory` would require big changes to this library - every entrypoint to fetch credentials, would need an additional overload to supply the factory and pass the instance around.

To make the code backwards-compatible, we'd need to detect the presence of `JsonFactory` implementations to detect a default (possible). Dependency-wise, we'd still need to pick a default factory so the library would work out of the box.

Alternatively, we could switch our parser to Gson (drop-in replacement) as our security team is promoting gson over jackson.

**Comment by elharo** [comment]
@chingor13 Can you forward me a reference to the security team's recommendation to use GSON instead of Jackson? Thanks.

**Comment by elharo** [comment]
I opened https://github.com/googleapis/google-http-java-client/issues/1208 to capture this work. 

I don't see an explicit dependency on fasterxml in this project.

**Comment by medb** [comment]
@elharo This library has a hardcoded dependency on `com.google.api.client.json.jackson2.JacksonFactory` which is wrapper around FasterXML Jackson library: https://github.com/googleapis/google-auth-library-java/search?q=jacksonfactory&type=code

I think that we need to reopen this issue, if we want to address it at some point.

**Comment by medb** [comment]
Regarding Gson vs Jackson, I also curious if there are any performance related considerations when choosing one over another?

**Comment by elharo** [comment]
That is **not** a dependency on jackson. `com.google.api.client.json.jackson2.JacksonFactory` is not a part of Jackson, whatever the name says. It is from httpo-java-client, not Jackson.

**Comment by chingor13** [comment]
It's not a direct dependency, but it transitively requires Jackson.

**Comment by elharo** [comment]
Yes. That's why the fix belongs in google-http-java-client.

**Comment by chingor13** [comment]
Swapping out jackson would involve switching google-auth-library's usage/dependency to the `google-http-client-gson` artifact from `google-http-client-jackson`.

**Comment by elharo** [comment]
Nor necessarily. We can keep google-http-client-jackson artifact and its one public class by swapping the internal private implementation.
