### ISSUE TITLE
The ComputeEngineCredentials auto-detection timeout is too tight

### ISSUE THREAD

**Issue by arithmetic1728** [googleapis/google-auth-library-java#517]
The autodetection logic in google-auth-library-java uses a 1.5 second timeout (3 tries at 0.5 seconds per try) before deciding that it isn't running on Compute Engine.

Unfortunately, 1.5 seconds is a little tight for GKE Workload Identity / gke-metadata-server, since it needs to wait for IP address information to bounce around between kube-apiserver and the node.

A timeout more like 10 seconds would go a long way towards making the autodetection more stable. Or, perhaps the client library could look for a "I'm definitely running on Compute Engine" environment variable.

**Comment by lesv** [comment]
@arithmetic1728 Are you still working on this?

**Comment by arithmetic1728** [comment]
@lesv No. The PR is already here, but it seems there are some disagreement.

**Comment by lesv** [comment]
I'm going to close this as several of the ancillary bugs are closed as well.

Feel free to reopen if you disagree.
