### ISSUE TITLE
GoogleCredentials createScoped does not do anything.

### ISSUE THREAD

**Issue by RobinGoussey** [googleapis/google-auth-library-java#585]
Hi,

The class GoogleCredentials createScoped does nothing, is this expected?`I'm following some online examples, and it still failed, after looking into the code, I see the method has no use?

Could the methods be deleted, or the implementation changed?
```
package com.google.auth.oauth2;
public class GoogleCredentials extends OAuth2Credentials {

  public GoogleCredentials createScoped(Collection<String> scopes) {
    return this;
  }

  public GoogleCredentials createScoped(String... scopes) {
    return this.createScoped((Collection)ImmutableList.copyOf(scopes));
  }
```

**Comment by Neenu1995** [comment]
GoogleCredentials is a base type for credentials and in that sense acts as an abstract class. The usual use case is to use `GoogleCredentials.getApplicationDefault()` which returns a subclass instance as "GoogleCredentials". All relevant sub classes like ServiceAccountCredentials, ComputeEngineCredentials etc have their own createScoped method implemented. Here is an [example](https://github.com/googleapis/google-auth-library-java/blob/4f8f79c601c54c66aa1a7a34be01af03e24079cf/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L129).
