### ISSUE TITLE
grpc-auth's unit test stopped working after google-auth-library 0.25.0

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-auth-library-java#620]
Also filed in https://github.com/grpc/grpc-java/issues/8037 as I haven't figured whether this is grpc-auth's bug or google-auth-library's.

# Failure

```
suztomo-macbookpro44% ./gradlew :grpc-auth:test
*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

> Task :grpc-auth:test

io.grpc.auth.GoogleAuthLibraryCallCredentialsTest > jwtAccessCredentialsInRequestMetadata FAILED
    org.junit.ComparisonFailure: expected:<https://example.com[:123/a.service]> but was:<https://example.com[/]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.grpc.auth.GoogleAuthLibraryCallCredentialsTest.jwtAccessCredentialsInRequestMetadata(GoogleAuthLibraryCallCredentialsTest.java:397)

16 tests completed, 1 failed

> Task :grpc-auth:test FAILED
```

# How to reproduce

Checkout grpc-java repository and change google-auth-library dependency:

```
suztomo-macbookpro44% git diff                 
diff --git a/build.gradle b/build.gradle
index 9baf8e029..81fbc4d86 100644
--- a/build.gradle
+++ b/build.gradle
@@ -56,7 +56,7 @@ subprojects {
 
         nettyVersion = '4.1.52.Final'
         guavaVersion = '30.0-android'
-        googleauthVersion = '0.22.2'
+        googleauthVersion = '0.25.2'
         protobufVersion = '3.12.0'
         protocVersion = protobufVersion
         opencensusVersion = '0.28.0'
```

The test works fine in 0.24.1 (just before 0.25.0).

@arithmetic1728 It seems that some behavioral change was introduced in 0.25.0 version. The only change in 0.25.0s' release note was your PR. Do you think the behavior change on the library (`ComparisonFailure: expected:<https://example.com[:123/a.service]> but was:<https://example.com[/]>`) was expected or not?

**Comment by arithmetic1728** [comment]
Yes it is the expected behavior. The reason is in RequestMetadata function of JWT credentials, we extract the `http(s)://host_name/` part from the uri and use that as the audience instead of using the original uri. The port `123` and the path `/a.service` are ignored in this example.
