### ISSUE TITLE
RequestMetadataCallback.onFailure() should provide a type-safe method to retrieve the root cause of the failure

### ISSUE THREAD

**Issue by nwbirnie** [googleapis/google-auth-library-java#626]
This caused issue: [googleapis/gax-java#965](https://github.com/googleapis/gax-java/issues/965) which is being investigated by grpc team here: https://github.com/grpc/grpc-java/issues/6808

## Description
The following is what happens.

1. If refresh token is invalid, then auth lib will throw an `HttpResponseException` like the following

    ```
    com.google.api.client.http.HttpResponseException: 400 Bad Request
    POST https://oauth2.googleapis.com/token
    {
      "error": "invalid_request",
      "error_description": "Could not determine client ID from request."
    }
    ```

1. [auth lib then passes the exception](https://github.com/googleapis/google-auth-library-java/blob/master/credentials/java/com/google/auth/Credentials.java#L114) to a `callback`

    ```
    protected final void blockingGetToCallback(URI uri, RequestMetadataCallback callback) {
        Map<String, List<String>result;
        try {
          result = getRequestMetadata(uri);
        } catch (Throwable e) {
          callback.onFailure(e);   <========= here
          return;
        }
        callback.onSuccess(result);
    }
    ```

1. callback is handled by the following code in grpc-auth [GoogleAuthLibraryCallCredentials.java](https://github.com/grpc/grpc-java/blob/master/auth/src/main/java/io/grpc/auth/GoogleAuthLibraryCallCredentials.java#L138)

    ```
    public void onFailure(Throwable e) {
        if (e instanceof IOException) {         <=============== here
          // Since it's an I/O failure, let the call be retried with UNAVAILABLE.
          applier.fail(Status.UNAVAILABLE
              .withDescription("Credentials failed to obtain metadata")
              .withCause(e));
        } else {
          applier.fail(Status.UNAUTHENTICATED
              .withDescription("Failed computing credential metadata")
              .withCause(e));
        }
    }
    ```

Note that `HttpResponseException` is subclass of `IOException`, but we shouldn't retry on `HttpResponseException`. So the correct implementation would be:

```
public void onFailure(Throwable e) {
        if ((e instanceof IOException) && !(e instanceof HttpResponseException)) {         <=============== here
          // Since it's an I/O failure, let the call be retried with UNAVAILABLE.
          applier.fail(Status.UNAVAILABLE
              .withDescription("Credentials failed to obtain metadata")
              .withCause(e));
        } else {
          applier.fail(Status.UNAUTHENTICATED
              .withDescription("Failed computing credential metadata")
              .withCause(e));
        }
      }
```

**Describe the solution you'd like**
`HttpResponseException` is an implementation detail of google-auth-library-java. We'd like a typed exception returned here with properties for the error context.

```
public class AuthenticationException {
  public AuthErrorCode getError() {
    // returns AuthErrorCode.INVALID_REQUEST for the example above.
  }

  public String getErrorDescription() {
    // returns "Could not determine client ID from request." for the example above.
  }
}

public enum AuthErrorCode {
  UNAVAILABLE,
  UNAUTHENTICATED,
  INVALID_REQUEST
  ...
}
```

**Describe alternatives you've considered**
gRPC could modify the exception handling to check if the exception is a `HttpResponseException`. However, this is an implementation detail of google-auth-library-java and potentially not a reliable indicator that the request has failed permanently.

**Comment by nwbirnie** [comment]
Hey @Neenu1995 just wondering if you could advise whether this is feasible and if so a timeline please? This is causing issues for ads API users and we'd like to make sure that it gets closed out.

**Comment by Neenu1995** [comment]
Hi,
The Auth team is currently looking into the issue. This looks like a specific example of a larger problem, which is that errors that might happen during auth flows are not reported with a precision that allows to distinguish errors that are retryable (e.g. server momentarily overloaded) vs error that should not be retried (e.g. the credentials are wrong, and the request should not be retried without a change in the credentials). 
They can start after the next week, since they are OOO next week. A more clear timeline can be provided then.

**Comment by nwbirnie** [comment]
Friendly ping :)

**Comment by TimurSadykov** [comment]
@nwbirnie design in progress :)

**Comment by nwbirnie** [comment]
That's awesome, thankyou @TimurSadykov !

**Comment by szleoxu** [comment]
Fix this problem remember @me. Thank you very much.

https://groups.google.com/g/adwords-api/c/bZe4omTqSIc
