### ISSUE TITLE
Provide google-api-services BOM or compatibility matrix

### ISSUE THREAD

**Issue by haimraman** [googleapis/google-auth-library-java#675]
I am having some issue with versions mixing where in some cases I get no such method error and some cases different behaviours with the APIs.

This request is related in general to the google-api-services libraries, but I failed to find a stable location to open this request. So feel free to move it to a better location in the issues repostory. 

The key challenge here is to know which versions to use few service libraries using maven or a similar dependency management tools.

For example if my project includes the following APIs.
```
<dependency>
        <groupId>com.google.oauth-client</groupId>
        <artifactId>google-oauth-client</artifactId>
        <version></version>
    </dependency>
    <dependency>
        <groupId>com.google.api-client</groupId>
        <artifactId>google-api-client</artifactId>
        <version></version>
    </dependency>
    <dependency>
        <groupId>com.google.auth</groupId>
        <artifactId>google-auth-library-oauth2-http</artifactId>
        <version></version>
    </dependency>
    <dependency>
        <groupId>com.google.apis</groupId>
        <artifactId>google-api-services-gmail</artifactId>
        <version></version>
    </dependency>
    <dependency>
        <groupId>com.google.apis</groupId>
        <artifactId>google-api-services-admin-directory</artifactId>
        <version></version>
    </dependency>
```
My problem:
How would I choose the diffrent versions making sure all dependencies are compatible?

**Describe the solution you'd like**
Common practice is to provide  Bill of Materials (BOM) with verified compatibility between versions. 

**Describe alternatives you've considered**
Any alternative solutions maybe some kind of documentation with compatibility matrix. 

**Additional context**
Any other context or screenshots about the feature request.
https://stackoverflow.com/questions/67618093/looking-for-google-api-services-bom-or-compatibility-matrix

**Comment by TimurSadykov** [comment]
Hi, sorry for delay, there are common dependencies BOMs, those would be a better place to start: 
https://github.com/googleapis/java-shared-dependencies
https://github.com/googleapis/java-cloud-bom
