### ISSUE TITLE
 GoogleSignInAccount.zaa(jsonString) fails with JSONException. JSONObject["expirationTime"] not a string.

### ISSUE THREAD

**Issue by saurabhdtu** [googleapis/google-auth-library-java#683]
Hi, I am facing this peculiar issue where I am getting GoogleSignInAccount as null after my app is killed in release mode. By debugging and diving deep into the implementation in `com.google.android.gms.auth.api.signin.internal.Storage` and  `com.google.android.gms.auth.api.signin.GoogleSignInAccount`, I found that the exception was occurring on the `expirationTime` value obtained on signing in. The value is expected to be a `string` while parsing, but is found out to be` long`.

#### Environment details
I am using the 
"**com.google.android.gms:play-services-auth:19.0.0**" 
and 
"**com.google.gms:google-services:4.3.8**"

#### Steps to reproduce
  1. Create an android app with the following buildType config
   release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            useProguard true
            ext.alwaysUpdateBuildId = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
  2. Sign in with your google account
  3. Exit the app and do the hot restart, you will find you are logged in  as the static variable are persistent in this journey
  4. Kill the app from memory and do a cold start, the google account is not logged in .

#### Stack trace
```
Non-fatal Exception: org.json.JSONException: JSONObject["expirationTime"] not a string.
       at org.json.JSONObject.getString(JSONObject.java:840)
       at com.google.android.gms.auth.api.signin.GoogleSignInAccount.zaa(GoogleSignInAccount.java:6)
```
So in spite of having the data stored in shared preferences the GoogleAccount returned is null because it fails the parsing.

 
Also, I can see the expiration time is 3600s. What is to be done after an hour?
How's the refresh of token is to be handled on android? Whats the best way to achieve this?
Also, what's the purpose of silent login?
Thanks!

**Comment by chingor13** [comment]
This repository does not have the Android Auth library, so unfortunately we don't have context into these questions. The Android/Google Play Services team manages their support: https://developers.google.com/android/support (probably under "Google Sign-in")
