### ISSUE TITLE
Looking for a way to programatically access "Third Party Apps" accessing users Google Account Info

### ISSUE THREAD

**Issue by kalrashubham49** [googleapis/google-auth-library-java#728]
We are looking out for SCOPE in Google Oauth2 Library for access "Third Party Apps" and permissions given to them by user.
This feature is very much required form Users Point of view as dealing with Enterprises we came to know this is a very common scenario in which User wants to visualise all the Permission given to third party apps through Google Signin , 

Please help in case if it already there, or suggest how to move further

**Comment by TimurSadykov** [comment]
Ack, will update by Dec 1st

**Comment by TimurSadykov** [comment]
This library focuses on server to server communication within Google cloud. For end user auth scenarios i would suggest to look into Firebase auth libraries.
