### ISSUE TITLE
Error reading credentials from stream, 'type' field not specified.

### ISSUE THREAD

**Issue by serical** [googleapis/google-auth-library-java#795]
#### Environment details

1. [Create Web application credentials (web server app)](https://developers.google.com/workspace/guides/create-credentials#web)
2. OS type and version: macOS 10.15.6
3. Java version: java8
4. google-auth-library version(s): 1.3.0

#### Steps to reproduce
this is my json file :
```json
{
  "web": {
    "client_id": "xxxxx-xxxxx.apps.googleusercontent.com",
    "project_id": "xxxxx-xxxxx-xxxx",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "xxxxxx-xxxxx",
    "redirect_uris": ["http://localhost:8888/Callback"]
  }
}

```

#### Code example

```java
GoogleCredentials credentials = GoogleCredentials.fromStream(new FileInputStream("/path/to/credentials.json"));
credentials.refreshIfExpired();
AccessToken token = credentials.getAccessToken();
// OR
AccessToken token = credentials.refreshAccessToken();
```

#### Stack trace
```
java.io.IOException: Error reading credentials from stream, 'type' field not specified.

	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:166)
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:139)
```

how to solve this problem？

Thanks!

**Comment by chanseokoh** [comment]
Include a `type` field. [Reading the code](https://github.com/googleapis/google-auth-library-java/blob/8cf273815f197a8b6b3d08043151005456824cbc/oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java#L164-L179), I see the value should be either one of
- `authorized_user`
- `service_account`
- `external_account`
- `impersonated_service_account`

I think in the basic cases, it's usually either `authorized_user` or `service_account`. You should know which credentials you are dealing with.

Going to close it, but feel free to update.

**Comment by serical** [comment]
Yes I read this code before I opened issues

but the json file obtained through this tutorial [Create Web application credentials (web server app)](https://developers.google.com/workspace/guides/create-credentials#web) does not have a `type` attribute.

It’s exactly the same as  below. I didn’t modify any information except sensitive information.
```json
{
  "web": {
    "client_id": "xxxxx-xxxxx.apps.googleusercontent.com",
    "project_id": "xxxxx-xxxxx-xxxx",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "xxxxxx-xxxxx",
    "redirect_uris": ["http://localhost:8888/Callback"]
  }
}
```

so I don’t know how to do it

**Comment by chanseokoh** [comment]
I see. I wonder if these "web application credentials" are meant to be understood by `GoogleCredentials`, but actually, I am not an expert in auth. @TimurSadykov @silvolu any idea?

**Comment by Sita04** [comment]
GoogleCredentials.fromStream() accepts Service Account credentials, whereas your json file looks like OAuth2.0 Client IDs.
Please choose the class corresponding to your credential origin. 

(Refer: https://github.com/googleapis/google-auth-library-java/tree/main/oauth2_http/java/com/google/auth/oauth2)

Please let us know if this solved the issue.

**Comment by TimurSadykov** [comment]
Thanks @Sita04 

closing since a solution was provided
