### ISSUE TITLE
GMail Scopes: Accessing non workspace accounts

### ISSUE THREAD

**Issue by rjosefsberg** [googleapis/google-auth-library-java#858]
OS: macOS Big Sur
Java Version: Temurin 11 (Adopt OpenJDK 11)

Hello,

For my use case I'm attempting to access a non-workspace Gmail account (user@gmail.com) using OAuth credentials. I have an application that performs the redirects and stores the keys and tokens. Thus far I have

* Created my OAuth consent screen. 
* Set the app to Testing
* Added the user account as a Test User
* Added the scope `https://mail.google.com/` to the app
* Generated a Client Id and Secret
* Authenticated as the user and retrieved the refresh token. 

In order to test a number of different avenues I have created a test class and I have taken the clientId/secret/refresh token and plugged them in as follows:

```java

GoogleCredentials credentials = UserCredentials.newBuilder()
                    .setClientId("[clientId]")
                    .setClientSecret("[secret]")
                    .setRefreshToken("[refresh token]")
                    .build();
credentials = credentials.createScoped("https://mail.google.com/");
credentials.refreshAccessToken();
Gmail gmail = new Gmail.Builder(new NetHttpTransport(), new GsonFactory(), new HttpCredentialsAdapter(credentials)).setApplicationName("[my app]").build();

ListMessagesResponse execute = gmail.users().messages().list("user@gmail.com").execute();

```

I receive the following response

```json

{
  "code": 403,
  "details": [
    {
      "@type": "type.googleapis.com/google.rpc.ErrorInfo",
      "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
    }
  ],
  "errors": [
    {
      "domain": "global",
      "message": "Insufficient Permission",
      "reason": "insufficientPermissions"
    }
  ],
  "message": "Request had insufficient authentication scopes.",
  "status": "PERMISSION_DENIED"
}

```

Is the flow different for pulling a personal email account? The API explorer didn't seem to have an issue. Any insights on where I might be going wrong would appreciated.

**Comment by sai-sunder-s** [comment]
I am not able to repro the PERMISSION DENIED Error. I tried
- setting up an OAuth account using workspace account, logging in with non-workspace account and fetching the emails for the non-workspace account
- setting up an OAuth account using non-workspace account, logging in with non-workspace account and fetching the emails for the non-workspace account
- setting up an OAuth account using workspace account, logging in with workspace account and fetching the emails for the workspace account

All the 3 cases worked for me without any issues.

Not sure if it makes a difference, but I generated the refresh token through `gcloud auth application-default login --client-id-file=<json of the oauth client> --scopes=https://mail.google.com/` and fetched the refresh token from `.config/gcloud/application_default_credentials.json`.

If you are still facing the problem, please reopen the issue.
