### ISSUE TITLE
Add support for local web server auth flow

### ISSUE THREAD

**Issue by chanseokoh** [googleapis/google-auth-library-java#88]
Something like [`LocalServerReceiver` in google-oauth-client](https://github.com/google/google-oauth-java-client/blob/dev/google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java).

**Comment by chingor13** [comment]
This is outside the scope of this repository. The implementation(s) in `google-oauth-client` integrate with several Java frameworks and will work with any OAuth2 implementation (not just Google's). 

Once you receive your credentials from the OAuth flow, you can instantiate a `Credentials` implementation here:

```java
// import com.google.auth.Credentials;
// import com.google.auth.oauth2.AccessToken;
// import com.google.auth.oauth2.OAuth2Credentials;

AccessToken accessToken = new AccessToken(
    "your-access-token-from-auth-flow", expirationFromAuthFlow);
Credentials credentials = OAuth2Credentials.create(accessToken);
```
