### ISSUE TITLE
Make it easy to convert a Pkcs8 encoded string to PrivateKey

### ISSUE THREAD

**Issue by navina** [googleapis/google-auth-library-java#883]
**Is your feature request related to a problem? Please describe.**
I am using `ServiceAccountCredentials.Builder` to parse my user provided credentials (via file / json). The `setPrivateKey` method accepts an instance of `PrivateKey`, where as the user provides a Pkcs8 string. The parsing method `privateKeyFromPkcs8` is package private only. So, I have to make a copy of this method implementation in my package and use it. This is inconvenient and prone to error when if there are changes across versions.

**Describe the solution you'd like**
Can this parsing method `privateKeyFromPkcs8` be made public ? Alternatively, can you provide a `setPrivateKeyString` method in the `ServiceAccountCredentials.Builder` class that will accept an Pkcs8 encoded string?

**Comment by TimurSadykov** [comment]
@navina thanks for surfacing the issue. The builder alternative looks fair, if you have time, you can prepare the change and that will speed up things.

**Comment by navina** [comment]
Gave it a go - https://github.com/googleapis/google-auth-library-java/pull/889 
Please take a look @TimurSadykov !
