### ISSUE TITLE
Cannot use this library on Android API version <26 as java.time.Duration was added in API 26

### ISSUE THREAD

**Issue by ashishb** [googleapis/google-auth-library-java#885]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: Android API version < 26
3. Java version: Java 8
4.  version(s):

#### Steps to reproduce

  1. Create `GoogleCredentials` object
  2. App will crash

#### Code example

```java
// example
    InputStream in =
        context.getResources().openRawResource(R.raw.google_service_account);
    return GoogleCredentials.fromStream(in).createScoped(Arrays.asList(SCOPES));
```

#### Stack trace
```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
  E      at com.google.auth.oauth2.OAuth2Credentials.<clinit>(OAuth2Credentials.java:70)
  E      at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredential
                            s.java:139)
```

#### External references such as API reference guides

- https://developer.android.com/reference/java/time/Duration
- https://github.com/googleapis/google-auth-library-java/blob/f9a9b8ace0199e6b75ed42c7bacfa3be30c34111/oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java#L43

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by TimurSadykov** [comment]
@ashishb Hey, this library targets server-to-server scenarios. For Android please take a look at https://developers.google.com/android/guides/api-client

**Comment by ashishb** [comment]
@TimurSadykov that's the library I'm using. I presumed that this is the source code for that library.
