### ISSUE TITLE
Outdated and misleading code examples in README.md

### ISSUE THREAD

**Issue by leifericf** [googleapis/google-auth-library-java#894]
The following code example is provided in `README.md`:

```
GoogleCredentials credentials = GoogleCredentials.fromStream(new FileInputStream("/path/to/credentials.json"));
credentials.refreshIfExpired();
AccessToken token = credentials.getAccessToken();
// OR
AccessToken token = credentials.refreshAccessToken();
```

Notice that `GoogleCredential` is marked as deprecated in https://googleapis.dev/java/google-api-client/latest/

Please update `README.md` to reflect current libraries and recommendations.

**Comment by TimurSadykov** [comment]
Hi @leifericf, the GoogleCredential != GoogleCredential**s**. Last letter matters :) The former is part of https://github.com/googleapis/google-oauth-java-client and is indeed deprecated, but the latter is part of this library and is current. 

Please reply if any questions.
