### ISSUE TITLE
java.io.IOException: Error getting access token for service account

### ISSUE THREAD

**Issue by jcdesignweb** [googleapis/google-auth-library-java#942]
Hi guys! 

I am using the 1.4.0 version of com.google.auth:google-auth-library-oauth2-http library and sometimes I get this error:

`java.io.IOException: Error getting access token for service account: Remote host closed connection during handshake, iss: firebase-adminsdk-xxxxx@xxx.iam.gserviceaccount.com
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:605)`

I don't know really how to solve this, this is affecting production and I need to solve this as soon as I can.

this is the code I wrote to get the AccessToken: 

```private String refreshAccessToken() throws IOException {

        GoogleCredentials googleCredentials = GoogleCredentials
                .fromStream(classPathJsonfile.getInputStream())
                .createScoped(Arrays.asList(SCOPES));
        AccessToken token = googleCredentials.refreshAccessToken();

        this.token = token.getTokenValue();
        this.expireOn = token.getExpirationTime().getTime();

        return this.token;
    }
```

Thanks!

**Comment by TimurSadykov** [comment]
Hi @jcdesignweb , sorry for a delay, did you find the root cause?

**Comment by westarle** [comment]
Please reopen if you're still experiencing this issue.
