### ISSUE TITLE
In-memory CredentialSource for IdentityPoolCredentials

### ISSUE THREAD

**Issue by fkorotkov** [googleapis/google-auth-library-java#952]
**Is your feature request related to a problem? Please describe.**

Right now it's only possible to create `IdentityPoolCredentials` from either a file locally presented on the machine or via a url like metadata server. It will be great to have an option to just be able to provide the contents of the token directly in the config file so I don't have to manage two credentials files. 

Plus in my case I'd like to programmatically create credentials and manage them.

**Describe the solution you'd like**

Right now a config file for `IdentityPoolCredentials` looks like this:

```json
{
  "type": "external_account",
  "audience": "//iam.googleapis.com/projects/PROJECT_ID/locations/global/workloadIdentityPools/POOL_NAME/providers/PROVIDER_NAME",
  "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
  "token_url": "https://sts.googleapis.com/v1/token",
  "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/cirrus-ci@PROJECT_NAME.iam.gserviceaccount.com:generateAccessToken",
  "credential_source": {
    "file": "/tmp/token.jwt",
    "format": {
      "type": "json",
      "subject_token_field_name": "access_token"
    }
  }
}
```

It will be great if I could provide `credential_source` as someting like this:

```json
{
    "text": "...",  #JWT token here
    "format": {
      "type": "json",
      "subject_token_field_name": "access_token"
    }
```

**Describe alternatives you've considered**

I've tried to just create a temp file for the credentials and use but in a multithreading environment and with a long lived nature of the tokens due to refreshing mechanism it's impossible to clean up the such temp files.

**Comment by fkorotkov** [comment]
I just implemented OIDC for AWS and their SDK has this awesome [AssumeRoleWithWebIdentityRequest#setWebIdentityToken](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/model/AssumeRoleWithWebIdentityRequest.html#setWebIdentityToken-java.lang.String-) to provide the token as plain text which was very pleasant to use when you need to create bunch of clients with different tokens on demand.

**Comment by lsirac** [comment]
Hi @fkorotkov, https://github.com/googleapis/google-auth-library-java/pull/1336 provides a way to provide your own retrieveSubjectToken() implementation. This way the token can be refreshed.
